import type { Party } from "./types";

// Supabase 연동 전 데모 데이터
export const DUMMY_PARTIES: Party[] = [
  {
    id: "p1",
    title: "애월 해안도로 자전거 라이딩",
    category: "cycling",
    description: "애월항에서 한림항까지 25km 해안도로 라이딩! 렌트 카니발 있어서 자전거 3대 실을 수 있어요. 중간에 카페 한잔 하고 갈 예정입니다.",
    date: "2026-04-12",
    time: "10:00",
    region: "애월",
    location: "애월항 주차장 집합",
    maxMembers: 4,
    currentMembers: 1,
    costType: "split",
    costAmount: 30000,
    hasRentalCar: true,
    carInfo: "카니발 9인승 (자전거 3대 가능)",
    rentalCarMode: "rent-together",
    rentalCarId: "carnival",
    rentalCarDailyPrice: 89000,
    rentalCarDays: 1,
    rentalCarPerPerson: 22250,
    rentalCarPickup: "제주공항점",
    rentalCarReturn: "제주공항점",
    rentalCarConfirmed: 1,
    equipmentNeeded: "자전거 (없으면 애월 렌탈샵에서 빌릴 수 있어요 ₩15,000/일)",
    hostName: "라이더김",
    hostRating: 4.8,
    hostPartyCount: 12,
    hostBio: "제주 한달살이 중, 자전거 매일 타요",
    tags: ["자전거", "해안도로", "애월", "렌터카있음"],
    schedule: [
      { time: "10:00", place: "애월항 주차장 집합", memo: "자전거 내리고 준비" },
      { time: "10:30", place: "애월항 출발", memo: "해안도로 라이딩 시작" },
      { time: "11:30", place: "곽지해변", memo: "잠깐 쉬면서 사진" },
      { time: "12:00", place: "카페 델문도", memo: "아메리카노 한잔" },
      { time: "12:40", place: "다시 출발 → 한림 방향" },
      { time: "13:30", place: "한림항 도착", memo: "라이딩 끝!" },
      { time: "14:00", place: "한림 우진해장국", memo: "몸국으로 마무리" },
      { time: "15:00", place: "렌터카로 애월 복귀 → 해산" },
    ],
    createdAt: "2026-04-09T10:00:00Z",
  },
  {
    id: "p2",
    title: "한라산 영실코스 같이 올라가실 분!",
    category: "hiking",
    description: "영실코스 왕복 약 5시간. 새벽 출발이라 렌터카 같이 타고 갈 분 모집합니다. 하산 후 흑돼지 먹으러 가요!",
    date: "2026-04-13",
    time: "05:30",
    region: "제주시",
    location: "제주시 연동 GS25 앞 (새벽 픽업)",
    maxMembers: 3,
    currentMembers: 2,
    costType: "split",
    costAmount: 25000,
    hasRentalCar: true,
    carInfo: "투싼 SUV",
    rentalCarMode: "rent-together",
    rentalCarId: "tucson",
    rentalCarDailyPrice: 59000,
    rentalCarDays: 1,
    rentalCarPerPerson: 19667,
    rentalCarPickup: "제주시 연동점",
    rentalCarReturn: "제주시 연동점",
    rentalCarConfirmed: 2,
    equipmentNeeded: "등산화, 따뜻한 옷 필수 (산 위 10도 이하)",
    hostName: "오름러버",
    hostRating: 4.9,
    hostPartyCount: 23,
    hostBio: "오름 100개 도전 중 (현재 67개)",
    tags: ["등산", "한라산", "영실", "새벽출발", "흑돼지"],
    schedule: [
      { time: "05:30", place: "제주시 연동 픽업" },
      { time: "06:30", place: "영실 탐방로 입구", memo: "등산 시작" },
      { time: "09:00", place: "윗세오름 대피소", memo: "간식 타임" },
      { time: "11:30", place: "하산 완료" },
      { time: "12:30", place: "흑돈가 (애월)", memo: "흑돼지 점심!" },
    ],
    createdAt: "2026-04-09T08:00:00Z",
  },
  {
    id: "p3",
    title: "서귀포 올레시장 → 카페 3곳 투어",
    category: "cafe",
    description: "올레시장에서 점심 먹고, 서귀포 숨은 카페 3곳 돌아볼 예정. 각자 이동이지만 같이 다니면 재밌잖아요 :)\n\n카페패스 있으면 음료 다 무료! 저도 3일권 쓸 예정이에요.",
    date: "2026-04-11",
    time: "12:00",
    region: "서귀포",
    location: "서귀포 올레시장 입구",
    maxMembers: 6,
    currentMembers: 3,
    costType: "free",
    hasRentalCar: false,
    hostName: "카페중독",
    hostRating: 4.6,
    hostPartyCount: 8,
    hostBio: "제주 카페 200곳 다녀봤어요",
    tags: ["카페", "서귀포", "올레시장", "맛집", "도보"],
    cafePassEnabled: true,
    cafePassNote: "5곳 다 제휴 카페예요. 3일권이면 다 커버됩니다!",
    cafeTourId: "ct2",
    schedule: [
      { time: "12:00", place: "서귀포 올레시장", memo: "점심 먹기 — 흑돼지 김밥 추천" },
      { time: "13:00", place: "카페소롱", memo: "한라봉 에이드 ☕ 패스 사용" },
      { time: "13:40", place: "빈브라더스 서귀포", memo: "핸드드립 ☕ 패스 사용" },
      { time: "14:20", place: "풍림다원", memo: "제주 녹차 체험 ☕ 패스 사용" },
      { time: "15:00", place: "이니스프리 제주하우스", memo: "그린티 세트 ☕ 패스 사용" },
      { time: "16:00", place: "해산 — 다음에 또 만나요!" },
    ],
    createdAt: "2026-04-09T09:30:00Z",
  },
  {
    id: "p4",
    title: "중문 서핑 초보 레슨 같이 받아요",
    category: "surfing",
    description: "중문 색달해변 서핑 레슨 2시간짜리 같이 신청하면 그룹 할인 들어가요! 끝나고 근처 맛집 갈 예정.",
    date: "2026-04-14",
    time: "14:00",
    region: "중문",
    location: "색달해변 제주서핑스쿨 앞",
    maxMembers: 4,
    currentMembers: 1,
    costType: "fixed",
    costAmount: 55000,
    hasRentalCar: false,
    equipmentNeeded: "수영복, 타올 (서핑보드/슈트 대여 포함)",
    hostName: "파도타기",
    hostRating: 4.3,
    hostPartyCount: 3,
    hostBio: "서핑 배우고 싶어서 제주 왔어요",
    tags: ["서핑", "초보환영", "중문", "그룹할인"],
    createdAt: "2026-04-09T11:00:00Z",
  },
  {
    id: "p5",
    title: "우도 전기자전거 + 땅콩아이스크림",
    category: "cycling",
    description: "우도에서 전기자전거 타고 한바퀴! 하고수동해변, 검멀레해변 들르고 땅콩아이스크림 먹어요. 성산항에서 배 같이 타요.",
    date: "2026-04-12",
    time: "09:00",
    region: "우도",
    location: "성산항 여객터미널",
    maxMembers: 5,
    currentMembers: 2,
    costType: "split",
    costAmount: 35000,
    hasRentalCar: true,
    carInfo: "레이 (성산항까지 이동용)",
    rentalCarMode: "rent-together",
    rentalCarId: "ray",
    rentalCarDailyPrice: 33000,
    rentalCarDays: 1,
    rentalCarPerPerson: 6600,
    rentalCarPickup: "성산점",
    rentalCarReturn: "성산점",
    rentalCarConfirmed: 2,
    hostName: "우도매니아",
    hostRating: 4.7,
    hostPartyCount: 15,
    hostBio: "우도 10번째 방문, 숨은 스팟 다 알아요",
    tags: ["우도", "전기자전거", "바다", "아이스크림"],
    createdAt: "2026-04-09T07:00:00Z",
  },
  {
    id: "p6",
    title: "월정리 일출 → 김녕 해안 러닝 10km",
    category: "running",
    description: "새벽 일출 보고 해안 따라 러닝! 김녕까지 약 10km 코스. 페이스 6분대로 천천히 갑니다. 끝나고 카페에서 브런치!",
    date: "2026-04-15",
    time: "05:50",
    region: "구좌",
    location: "월정리해변 주차장",
    maxMembers: 6,
    currentMembers: 1,
    costType: "free",
    hasRentalCar: false,
    equipmentNeeded: "러닝화, 물, 가벼운 간식",
    hostName: "새벽러너",
    hostRating: 4.5,
    hostPartyCount: 6,
    hostBio: "마라톤 sub4, 제주 해안 러닝 코스 개척 중",
    tags: ["러닝", "일출", "월정리", "해안도로"],
    createdAt: "2026-04-09T12:00:00Z",
  },
  {
    id: "p7",
    title: "서귀포 방파제 낚시 반나절",
    category: "fishing",
    description: "서귀포 법환포구 방파제에서 반나절 낚시. 장비 여분 있어서 초보도 환영! 잡은 회 근처 횟집에서 떠먹어요.",
    date: "2026-04-13",
    time: "06:00",
    region: "서귀포",
    location: "법환포구 방파제",
    maxMembers: 3,
    currentMembers: 1,
    costType: "split",
    costAmount: 15000,
    hasRentalCar: true,
    carInfo: "스타렉스 (장비 다 실림)",
    rentalCarMode: "own-car",
    equipmentNeeded: "없음 (여분 장비 제공, 미끼비만 분담)",
    hostName: "바다사나이",
    hostRating: 4.9,
    hostPartyCount: 19,
    hostBio: "제주 토박이, 포인트 다 알아요",
    tags: ["낚시", "초보환영", "방파제", "회"],
    createdAt: "2026-04-09T06:00:00Z",
  },
  {
    id: "p9",
    title: "애월 감성 카페 5곳 호핑 투어",
    category: "cafe",
    description: "애월 해안도로 따라 오션뷰 카페 5곳을 돌아요! 렌터카로 이동하고, 각 카페에서 30분씩 여유롭게. 사진 맛집만 엄선했어요 📸",
    date: "2026-04-19",
    time: "11:00",
    region: "애월",
    location: "애월항 주차장",
    maxMembers: 4,
    currentMembers: 1,
    costType: "split",
    costAmount: 15000,
    hasRentalCar: true,
    carInfo: "레이 (4인 딱 맞음)",
    rentalCarMode: "rent-together",
    rentalCarId: "ray",
    rentalCarDailyPrice: 33000,
    rentalCarDays: 1,
    rentalCarPerPerson: 8250,
    rentalCarPickup: "애월점",
    rentalCarReturn: "애월점",
    rentalCarConfirmed: 1,
    hostName: "카페헌터",
    hostRating: 4.9,
    hostPartyCount: 31,
    hostBio: "제주 카페 블로거, 300곳 방문 기록 중",
    tags: ["카페", "애월", "오션뷰", "감성", "사진"],
    cafePassEnabled: true,
    cafePassNote: "5곳 다 가는데 카페패스 있으면 거의 공짜! 저는 3일권 추천",
    cafeTourId: "ct1",
    schedule: [
      { time: "11:00", place: "카페 델문도", memo: "바다뷰 아메리카노 ☕ 패스 사용" },
      { time: "11:40", place: "봄날", memo: "귤라떼 ☕ 패스 사용" },
      { time: "12:20", place: "어도어하우스", memo: "감귤밭 뷰 + 말차라떼 ☕ 패스 사용" },
      { time: "13:00", place: "점심 (협재 근처)", memo: "해물라면 or 회" },
      { time: "14:00", place: "레이지펌프", memo: "코코넛 라떼 ☕ 패스 사용" },
      { time: "14:40", place: "해녀의부엌 카페", memo: "해녀 에스프레소 ☕ 패스 사용" },
      { time: "15:30", place: "애월항 복귀 → 해산" },
    ],
    createdAt: "2026-04-15T14:00:00Z",
  },
  {
    id: "p8",
    title: "제주 동쪽 포토스팟 5곳 출사 투어",
    category: "photo",
    description: "성산일출봉 → 섭지코지 → 광치기해변 → 세화해변 → 월정리. 카메라/폰 상관없이 사진 좋아하는 분 모여요!",
    date: "2026-04-11",
    time: "08:00",
    region: "성산",
    location: "성산일출봉 주차장",
    maxMembers: 4,
    currentMembers: 2,
    costType: "split",
    costAmount: 20000,
    hasRentalCar: true,
    carInfo: "쏘렌토 (넓어서 삼각대도 가능)",
    rentalCarMode: "own-car",
    hostName: "제주포토",
    hostRating: 4.7,
    hostPartyCount: 11,
    hostBio: "사진작가, 제주 사진집 출간 준비 중",
    tags: ["출사", "포토", "성산", "일출", "해변"],
    createdAt: "2026-04-09T13:00:00Z",
  },
];
