export interface PartnerOffer {
  id: string;
  businessName: string;
  businessType: "guesthouse" | "cafe" | "tourist-spot" | "restaurant" | "activity" | "rental";
  emoji: string;
  location: string;
  offerType: "discount" | "freebie" | "package";
  offerTitle: string;
  offerDetail: string;
  discountCode?: string;
  discountPercent?: number;
  /** 할인율 계산의 기준이 되는 정가 (원). 절약 금액 표시에 사용 */
  basePrice?: number;
  targetCategories: string[];
  sponsorLevel: "basic" | "featured";
  validUntil: string;
}

export const PARTNER_OFFERS: PartnerOffer[] = [
  {
    id: "po1",
    businessName: "서퍼스 게스트하우스",
    businessType: "guesthouse",
    emoji: "🏄",
    location: "서귀포 중문",
    offerType: "discount",
    offerTitle: "파티 참가자 숙박 15% 할인",
    offerDetail: "앱 파티 참가 화면 제시 후 체크인 시 즉시 적용. 1박 이상 예약, 성수기(7~8월) 제외",
    discountCode: "PARTY2026",
    discountPercent: 15,
    basePrice: 80000,
    targetCategories: ["surfing", "all"],
    sponsorLevel: "featured",
    validUntil: "2026-12-31",
  },
  {
    id: "po2",
    businessName: "중문 서핑 장비 렌탈",
    businessType: "rental",
    emoji: "🛹",
    location: "서귀포 색달해변",
    offerType: "discount",
    offerTitle: "서핑보드 + 슈트 10% 할인",
    offerDetail: "앱 화면 제시 또는 코드 입력 시 당일 렌탈 10% 할인. 3인 이상 그룹은 추가 5% 중복 적용",
    discountCode: "SURF10",
    discountPercent: 10,
    basePrice: 30000,
    targetCategories: ["surfing"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
  {
    id: "po3",
    businessName: "한라산 베이스캠프",
    businessType: "guesthouse",
    emoji: "⛺",
    location: "제주시 아라동",
    offerType: "package",
    offerTitle: "등산 전날 숙박 + 조식 패키지",
    offerDetail: "앱 파티 참가 화면 제시 시 새벽 출발 파티 참가자 전용가 적용. 04:00 조기 체크아웃 가능, 조식 포함",
    discountCode: "HIKE2026",
    discountPercent: 20,
    basePrice: 80000,
    targetCategories: ["hiking"],
    sponsorLevel: "featured",
    validUntil: "2026-12-31",
  },
  {
    id: "po4",
    businessName: "성산 등산 장비 대여",
    businessType: "rental",
    emoji: "🥾",
    location: "성산읍",
    offerType: "discount",
    offerTitle: "등산화·스틱 세트 15% 할인",
    offerDetail: "앱 화면 제시 또는 코드 입력 시 당일 대여 즉시 할인. 영실·성판악 코스 이용자 한정",
    discountCode: "TREK15",
    discountPercent: 15,
    basePrice: 25000,
    targetCategories: ["hiking"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
  {
    id: "po5",
    businessName: "제주 감귤 체험농장",
    businessType: "tourist-spot",
    emoji: "🍊",
    location: "서귀포 남원",
    offerType: "freebie",
    offerTitle: "감귤 따기 체험 음료 1잔 무료",
    offerDetail: "앱 파티 참가 화면 제시 시 체험 당일 음료 1잔 무료 제공. 최소 1일 전 사전 예약 필수",
    discountCode: "CITRUS",
    basePrice: 15000,
    targetCategories: ["cafe", "food"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
  {
    id: "po6",
    businessName: "애월 오션뷰 디저트 카페",
    businessType: "cafe",
    emoji: "🍰",
    location: "애월 해안도로",
    offerType: "freebie",
    offerTitle: "음료 주문 시 디저트 1개 무료",
    offerDetail: "앱 화면 제시 또는 코드 입력 후 1인 1회 한정. 한라봉 타르트 또는 흑임자 케이크 중 선택",
    discountCode: "CAFE2026",
    basePrice: 12000,
    targetCategories: ["cafe"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
  {
    id: "po7",
    businessName: "흑돈가 흑돼지 전문점",
    businessType: "restaurant",
    emoji: "🐷",
    location: "애월읍",
    offerType: "discount",
    offerTitle: "흑돼지 1인분 10% 할인",
    offerDetail: "앱 파티 참가 화면 제시 시 3인 이상 테이블 전체 금액 10% 할인. 점심 런치 세트 메뉴 제외",
    discountCode: "PORK10",
    discountPercent: 10,
    basePrice: 12000,
    targetCategories: ["all"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
  {
    id: "po8",
    businessName: "성산일출봉 입장권 할인",
    businessType: "tourist-spot",
    emoji: "🌋",
    location: "성산읍 성산리",
    offerType: "discount",
    offerTitle: "성산일출봉 입장권 20% 할인",
    offerDetail: "앱 화면 제시 또는 코드 입력 시 1인 20% 즉시 할인. 5인 이상 단체는 추가 5% 중복 적용",
    discountCode: "ILCHUL20",
    discountPercent: 20,
    basePrice: 15000,
    targetCategories: ["photo", "hiking", "running", "all"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
  {
    id: "po9",
    businessName: "우도 전기자전거 렌탈샵",
    businessType: "rental",
    emoji: "⚡",
    location: "우도 천진항",
    offerType: "discount",
    offerTitle: "전기자전거 4시간 기준 10% 할인",
    offerDetail: "앱 화면 제시 또는 코드 입력 시 파티 팀 전체 동시 대여에 적용. 헬멧·자물쇠 무료 제공",
    discountCode: "EBIKE10",
    discountPercent: 10,
    basePrice: 20000,
    targetCategories: ["cycling"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
  {
    id: "po10",
    businessName: "제주 스노클링 투어",
    businessType: "activity",
    emoji: "🤿",
    location: "서귀포 섶섬 앞",
    offerType: "package",
    offerTitle: "스노클링 장비 + 가이드 패키지 15% 할인",
    offerDetail: "앱 파티 참가 화면 제시 시 전용 패키지가로 즉시 적용. 2인 이상 예약 필수, 현장 결제",
    discountCode: "SNORKEL15",
    discountPercent: 15,
    basePrice: 30000,
    targetCategories: ["surfing", "diving"],
    sponsorLevel: "basic",
    validUntil: "2026-12-31",
  },
];
