import type { Party } from "./types";

// Supabase 연동 전 데모 데이터
export const DUMMY_PARTIES: Party[] = [
  {
    id: "p1",
    title: "애월 해안도로 자전거 라이딩",
    category: "cycling",
    description: "애월항에서 한림항까지 25km 해안도로 라이딩! 렌트 카니발 있어서 자전거 3대 실을 수 있어요. 중간에 카페 한잔 하고 갈 예정입니다.",
    date: "2026-04-12",
    time: "10:00",
    region: "애월",
    location: "애월항 주차장 집합",
    maxMembers: 4,
    currentMembers: 1,
    costType: "split",
    costAmount: 30000,
    hasRentalCar: true,
    carInfo: "카니발 9인승 (자전거 3대 가능)",
    rentalCarMode: "rent-together",
    rentalCarId: "carnival",
    rentalCarDailyPrice: 89000,
    rentalCarDays: 1,
    rentalCarPerPerson: 22250,
    rentalCarPickup: "제주공항점",
    rentalCarReturn: "제주공항점",
    rentalCarConfirmed: 1,
    equipmentNeeded: "자전거 (없으면 애월 렌탈샵에서 빌릴 수 있어요 ₩15,000/일)",
    hostName: "라이더김",
    hostRating: 4.8,
    hostPartyCount: 12,
    hostBio: "제주 한달살이 중, 자전거 매일 타요",
    tags: ["자전거", "해안도로", "애월", "렌터카있음"],
    stopSlugs: ["cafe-del-mundo"],
    schedule: [
      { time: "10:00", place: "애월항 주차장 집합", memo: "자전거 내리고 준비" },
      { time: "10:30", place: "애월항 출발", memo: "해안도로 라이딩 시작" },
      { time: "11:30", place: "곽지해변", memo: "잠깐 쉬면서 사진" },
      { time: "12:00", place: "카페 델문도", memo: "아메리카노 한잔" },
      { time: "12:40", place: "다시 출발 → 한림 방향" },
      { time: "13:30", place: "한림항 도착", memo: "라이딩 끝!" },
      { time: "14:00", place: "한림 우진해장국", memo: "몸국으로 마무리" },
      { time: "15:00", place: "렌터카로 애월 복귀 → 해산" },
    ],
    createdAt: "2026-04-09T10:00:00Z",
  },
  {
    id: "p2",
    title: "한라산 영실코스 같이 올라가실 분!",
    category: "hiking",
    description: "영실코스 왕복 약 5시간. 새벽 출발이라 렌터카 같이 타고 갈 분 모집합니다. 하산 후 흑돼지 먹으러 가요!",
    date: "2026-04-13",
    time: "05:30",
    region: "제주시",
    location: "제주시 연동 GS25 앞 (새벽 픽업)",
    maxMembers: 3,
    currentMembers: 2,
    costType: "split",
    costAmount: 25000,
    hasRentalCar: true,
    carInfo: "투싼 SUV",
    rentalCarMode: "rent-together",
    rentalCarId: "tucson",
    rentalCarDailyPrice: 59000,
    rentalCarDays: 1,
    rentalCarPerPerson: 19667,
    rentalCarPickup: "제주시 연동점",
    rentalCarReturn: "제주시 연동점",
    rentalCarConfirmed: 2,
    equipmentNeeded: "등산화, 따뜻한 옷 필수 (산 위 10도 이하)",
    hostName: "오름러버",
    hostRating: 4.9,
    hostPartyCount: 23,
    hostBio: "오름 100개 도전 중 (현재 67개)",
    tags: ["등산", "한라산", "영실", "새벽출발", "흑돼지"],
    schedule: [
      { time: "05:30", place: "제주시 연동 픽업" },
      { time: "06:30", place: "영실 탐방로 입구", memo: "등산 시작" },
      { time: "09:00", place: "윗세오름 대피소", memo: "간식 타임" },
      { time: "11:30", place: "하산 완료" },
      { time: "12:30", place: "흑돈가 (애월)", memo: "흑돼지 점심!" },
    ],
    createdAt: "2026-04-09T08:00:00Z",
  },
  {
    id: "p3",
    title: "서귀포 올레시장 → 카페 3곳 투어",
    category: "cafe",
    description: "올레시장에서 점심 먹고, 서귀포 숨은 카페 3곳 돌아볼 예정. 각자 이동이지만 같이 다니면 재밌잖아요 :)\n\n카페패스 있으면 음료 다 무료! 저도 3일권 쓸 예정이에요.",
    date: "2026-04-11",
    time: "12:00",
    region: "서귀포",
    location: "서귀포 올레시장 입구",
    maxMembers: 6,
    currentMembers: 3,
    costType: "free",
    hasRentalCar: false,
    hostName: "카페중독",
    hostRating: 4.6,
    hostPartyCount: 8,
    hostBio: "제주 카페 200곳 다녀봤어요",
    tags: ["카페", "서귀포", "올레시장", "맛집", "도보"],
    cafePassEnabled: true,
    cafePassNote: "5곳 다 제휴 카페예요. 3일권이면 다 커버됩니다!",
    cafeTourId: "ct2",
    stopSlugs: ["cafe-solong", "bean-brothers-seogwipo", "pungrim-dawon", "innisfree-jeju"],
    schedule: [
      { time: "12:00", place: "서귀포 올레시장", memo: "점심 먹기 — 흑돼지 김밥 추천" },
      { time: "13:00", place: "카페소롱", memo: "한라봉 에이드 ☕ 패스 사용" },
      { time: "13:40", place: "빈브라더스 서귀포", memo: "핸드드립 ☕ 패스 사용" },
      { time: "14:20", place: "풍림다원", memo: "제주 녹차 체험 ☕ 패스 사용" },
      { time: "15:00", place: "이니스프리 제주하우스", memo: "그린티 세트 ☕ 패스 사용" },
      { time: "16:00", place: "해산 — 다음에 또 만나요!" },
    ],
    createdAt: "2026-04-09T09:30:00Z",
  },
  {
    id: "p4",
    title: "중문 서핑 초보 레슨 같이 받아요",
    category: "surfing",
    description: "중문 색달해변 서핑 레슨 2시간짜리 같이 신청하면 그룹 할인 들어가요! 끝나고 근처 맛집 갈 예정.",
    date: "2026-04-14",
    time: "14:00",
    region: "중문",
    location: "색달해변 제주서핑스쿨 앞",
    maxMembers: 4,
    currentMembers: 1,
    costType: "fixed",
    costAmount: 55000,
    hasRentalCar: false,
    equipmentNeeded: "수영복, 타올 (서핑보드/슈트 대여 포함)",
    hostName: "파도타기",
    hostRating: 4.3,
    hostPartyCount: 3,
    hostBio: "서핑 배우고 싶어서 제주 왔어요",
    tags: ["서핑", "초보환영", "중문", "그룹할인"],
    createdAt: "2026-04-09T11:00:00Z",
  },
  {
    id: "p5",
    title: "우도 전기자전거 + 땅콩아이스크림",
    category: "cycling",
    description: "우도에서 전기자전거 타고 한바퀴! 하고수동해변, 검멀레해변 들르고 땅콩아이스크림 먹어요. 성산항에서 배 같이 타요.",
    date: "2026-04-12",
    time: "09:00",
    region: "우도",
    location: "성산항 여객터미널",
    maxMembers: 5,
    currentMembers: 2,
    costType: "split",
    costAmount: 35000,
    hasRentalCar: true,
    carInfo: "레이 (성산항까지 이동용)",
    rentalCarMode: "rent-together",
    rentalCarId: "ray",
    rentalCarDailyPrice: 33000,
    rentalCarDays: 1,
    rentalCarPerPerson: 6600,
    rentalCarPickup: "성산점",
    rentalCarReturn: "성산점",
    rentalCarConfirmed: 2,
    hostName: "우도매니아",
    hostRating: 4.7,
    hostPartyCount: 15,
    hostBio: "우도 10번째 방문, 숨은 스팟 다 알아요",
    tags: ["우도", "전기자전거", "바다", "아이스크림"],
    createdAt: "2026-04-09T07:00:00Z",
  },
  {
    id: "p6",
    title: "월정리 일출 → 김녕 해안 러닝 10km",
    category: "running",
    description: "새벽 일출 보고 해안 따라 러닝! 김녕까지 약 10km 코스. 페이스 6분대로 천천히 갑니다. 끝나고 카페에서 브런치!",
    date: "2026-04-15",
    time: "05:50",
    region: "구좌",
    location: "월정리해변 주차장",
    maxMembers: 6,
    currentMembers: 1,
    costType: "free",
    hasRentalCar: false,
    equipmentNeeded: "러닝화, 물, 가벼운 간식",
    hostName: "새벽러너",
    hostRating: 4.5,
    hostPartyCount: 6,
    hostBio: "마라톤 sub4, 제주 해안 러닝 코스 개척 중",
    tags: ["러닝", "일출", "월정리", "해안도로"],
    createdAt: "2026-04-09T12:00:00Z",
  },
  {
    id: "p7",
    title: "서귀포 방파제 낚시 반나절",
    category: "fishing",
    description: "서귀포 법환포구 방파제에서 반나절 낚시. 장비 여분 있어서 초보도 환영! 잡은 회 근처 횟집에서 떠먹어요.",
    date: "2026-04-13",
    time: "06:00",
    region: "서귀포",
    location: "법환포구 방파제",
    maxMembers: 3,
    currentMembers: 1,
    costType: "split",
    costAmount: 15000,
    hasRentalCar: true,
    carInfo: "스타렉스 (장비 다 실림)",
    rentalCarMode: "own-car",
    equipmentNeeded: "없음 (여분 장비 제공, 미끼비만 분담)",
    hostName: "바다사나이",
    hostRating: 4.9,
    hostPartyCount: 19,
    hostBio: "제주 토박이, 포인트 다 알아요",
    tags: ["낚시", "초보환영", "방파제", "회"],
    createdAt: "2026-04-09T06:00:00Z",
  },
  {
    id: "p9",
    title: "애월 감성 카페 5곳 호핑 투어",
    category: "cafe",
    description: "애월 해안도로 따라 오션뷰 카페 5곳을 돌아요! 렌터카로 이동하고, 각 카페에서 30분씩 여유롭게. 사진 맛집만 엄선했어요 📸",
    date: "2026-04-19",
    time: "11:00",
    region: "애월",
    location: "애월항 주차장",
    maxMembers: 4,
    currentMembers: 1,
    costType: "split",
    costAmount: 15000,
    hasRentalCar: true,
    carInfo: "레이 (4인 딱 맞음)",
    rentalCarMode: "rent-together",
    rentalCarId: "ray",
    rentalCarDailyPrice: 33000,
    rentalCarDays: 1,
    rentalCarPerPerson: 8250,
    rentalCarPickup: "애월점",
    rentalCarReturn: "애월점",
    rentalCarConfirmed: 1,
    hostName: "카페헌터",
    hostRating: 4.9,
    hostPartyCount: 31,
    hostBio: "제주 카페 블로거, 300곳 방문 기록 중",
    tags: ["카페", "애월", "오션뷰", "감성", "사진"],
    cafePassEnabled: true,
    cafePassNote: "5곳 다 가는데 카페패스 있으면 거의 공짜! 저는 3일권 추천",
    cafeTourId: "ct1",
    stopSlugs: ["cafe-del-mundo", "bomnal", "odor-house", "lazy-pump", "haenyeo-kitchen"],
    schedule: [
      { time: "11:00", place: "카페 델문도", memo: "바다뷰 아메리카노 ☕ 패스 사용" },
      { time: "11:40", place: "봄날", memo: "귤라떼 ☕ 패스 사용" },
      { time: "12:20", place: "어도어하우스", memo: "감귤밭 뷰 + 말차라떼 ☕ 패스 사용" },
      { time: "13:00", place: "점심 (협재 근처)", memo: "해물라면 or 회" },
      { time: "14:00", place: "레이지펌프", memo: "코코넛 라떼 ☕ 패스 사용" },
      { time: "14:40", place: "해녀의부엌 카페", memo: "해녀 에스프레소 ☕ 패스 사용" },
      { time: "15:30", place: "애월항 복귀 → 해산" },
    ],
    createdAt: "2026-04-15T14:00:00Z",
  },
  {
    id: "p8",
    title: "제주 동쪽 포토스팟 5곳 출사 투어",
    category: "photo",
    description: "성산일출봉 → 섭지코지 → 광치기해변 → 세화해변 → 월정리. 카메라/폰 상관없이 사진 좋아하는 분 모여요!",
    date: "2026-04-11",
    time: "08:00",
    region: "성산",
    location: "성산일출봉 주차장",
    maxMembers: 4,
    currentMembers: 2,
    costType: "split",
    costAmount: 20000,
    hasRentalCar: true,
    carInfo: "쏘렌토 (넓어서 삼각대도 가능)",
    rentalCarMode: "own-car",
    hostName: "제주포토",
    hostRating: 4.7,
    hostPartyCount: 11,
    hostBio: "사진작가, 제주 사진집 출간 준비 중",
    tags: ["출사", "포토", "성산", "일출", "해변"],
    createdAt: "2026-04-09T13:00:00Z",
  },

  // ── 사업자 파티 ──────────────────────────────────────────────
  {
    id: "c1",
    partyType: "commercial",
    title: "서핑 입문 클래스 — 협재해변",
    category: "surfing",
    description: "서핑이 처음이어도 걱정 마세요! 제주웨이브서핑스쿨의 전문 강사가 2시간 동안 1:4 소그룹 레슨을 진행합니다. 보드와 슈트는 전부 제공되며, 레슨 중 사진 촬영도 해드려요.",
    date: "2026-05-10",
    time: "10:00",
    region: "한림",
    location: "협재해변 서핑 스쿨 앞",
    maxMembers: 8,
    currentMembers: 0,
    reservedSeats: 3,
    costType: "fixed",
    costAmount: 65000,
    hasRentalCar: false,
    operatorName: "제주웨이브서핑스쿨",
    operatorContact: "010-1234-5678",
    operatorVerified: true,
    pricePerSeat: 65000,
    depositRate: 100,
    platformFeeRate: 12,
    includedItems: ["서핑보드 대여", "슈트 대여", "2시간 전문 강습", "레슨 중 사진 촬영"],
    excludedItems: ["개인 음료", "식사"],
    refundPolicy: "3일 전 100%, 1일 전 50%, 당일 환불 불가",
    hostName: "제주웨이브서핑스쿨",
    hostRating: 4.9,
    hostPartyCount: 142,
    hostBio: "제주 서핑 전문 업체, 강사 5명 상주, 안전 최우선",
    tags: ["서핑", "입문", "협재해변", "장비포함", "사진촬영"],
    schedule: [
      { time: "10:00", place: "협재해변 스쿨 앞 집합", memo: "준비 및 장비 수령" },
      { time: "10:10", place: "해변", memo: "준비운동 및 스트레칭" },
      { time: "10:20", place: "스쿨 강의실", memo: "서핑 이론 교육 (안전 수칙)" },
      { time: "10:40", place: "협재해변 (수심 얕은 구역)", memo: "물 위 실습" },
      { time: "11:40", place: "협재해변", memo: "자유 서핑 & 사진 촬영" },
      { time: "12:00", place: "스쿨 샤워실", memo: "마무리 및 해산" },
    ],
    createdAt: "2026-04-20T09:00:00Z",
  },
  {
    id: "c2",
    partyType: "commercial",
    title: "성산일출봉 일출 가이드 투어",
    category: "hiking",
    description: "새벽 5시 제주시에서 출발해 일출 명소 성산일출봉까지 미니밴으로 편하게 이동! 현지 가이드의 해설과 함께 일출을 감상하고, 해녀의집에서 든든한 조식까지 즐겨요. 우도 추가 방문 옵션도 있어요.",
    date: "2026-05-15",
    time: "05:00",
    region: "성산",
    location: "제주시 동문시장 앞 (픽업)",
    maxMembers: 10,
    currentMembers: 0,
    reservedSeats: 6,
    costType: "fixed",
    costAmount: 45000,
    hasRentalCar: false,
    operatorName: "제주로컬가이드",
    operatorContact: "010-9876-5432",
    operatorVerified: false,
    pricePerSeat: 45000,
    depositRate: 50,
    platformFeeRate: 10,
    minMembers: 4,
    includedItems: ["미니밴 이동 (제주시 픽업)", "로컬 가이드 해설", "성산일출봉 입장료", "간식 1회"],
    excludedItems: ["조식 식사비 (해녀의집, 개인 부담)", "우도 추가 방문비"],
    refundPolicy: "2일 전 100%, 당일 50%",
    hostName: "제주로컬가이드",
    hostRating: 4.8,
    hostPartyCount: 89,
    hostBio: "제주 토박이 가이드, 숨은 스팟 전문",
    tags: ["일출", "성산일출봉", "가이드투어", "픽업포함", "입장료포함"],
    schedule: [
      { time: "05:00", place: "제주시 동문시장 앞 픽업" },
      { time: "06:10", place: "성산일출봉 도착", memo: "일출 감상 & 가이드 해설" },
      { time: "07:30", place: "해녀의집", memo: "조식 (개인 부담)" },
      { time: "09:00", place: "우도행 배편 (선택 옵션)" },
    ],
    createdAt: "2026-04-21T09:00:00Z",
  },
  {
    id: "c3",
    partyType: "commercial",
    title: "한라산 백록담 당일 가이드 등반 (성판악)",
    category: "hiking",
    description: "한라산 정상 백록담까지 성판악 코스로 전문 가이드와 함께 오릅니다. 안전한 등반을 위한 응급키트와 등반 보험이 포함되어 있으며, 가이드가 체력에 맞는 속도로 이끌어드립니다.",
    date: "2026-05-20",
    time: "05:30",
    region: "제주시",
    location: "성판악 탐방로 입구",
    maxMembers: 6,
    currentMembers: 0,
    reservedSeats: 2,
    costType: "fixed",
    costAmount: 80000,
    hasRentalCar: false,
    operatorName: "한라산전문가이드",
    operatorContact: "010-5555-7777",
    operatorVerified: false,
    pricePerSeat: 80000,
    depositRate: 30,
    platformFeeRate: 10,
    minMembers: 3,
    includedItems: ["전문 등반 가이드", "간식 2회 제공", "응급 처치 키트", "등반 보험"],
    excludedItems: ["개인 등산 장비", "입장료 (무료)", "교통편"],
    refundPolicy: "3일 전 전액, 1일 전 50%, 당일 불가 (날씨 취소 시 전액 환불)",
    hostName: "한라산전문가이드",
    hostRating: 4.9,
    hostPartyCount: 56,
    hostBio: "한라산 등반 전문, 안전 등반 10년 경력",
    tags: ["한라산", "백록담", "성판악", "가이드등반", "보험포함"],
    schedule: [
      { time: "05:30", place: "성판악 탐방로 입구 집합", memo: "장비 점검 및 스트레칭" },
      { time: "06:00", place: "성판악 코스 출발" },
      { time: "08:30", place: "사라오름 갈림길", memo: "간식 타임" },
      { time: "10:30", place: "백록담 정상", memo: "인증샷 & 휴식" },
      { time: "15:00", place: "성판악 하산 완료" },
    ],
    createdAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "c4",
    partyType: "commercial",
    title: "제주 해녀 체험 & 해산물 직접 요리",
    category: "diving",
    description: "현직 해녀 선생님과 함께 실제 해녀 장비를 착용하고 바다에서 해산물을 직접 채취합니다. 채취한 해산물로 해녀 선생님께 조리 방법을 배우며 직접 요리해 드시는 3시간 체험 프로그램입니다.",
    date: "2026-05-25",
    time: "10:00",
    region: "성산",
    location: "성산읍 해녀문화원 앞",
    maxMembers: 6,
    currentMembers: 0,
    reservedSeats: 4,
    costType: "fixed",
    costAmount: 120000,
    hasRentalCar: false,
    operatorName: "성산해녀문화원",
    operatorContact: "064-782-0000",
    operatorVerified: true,
    pricePerSeat: 120000,
    depositRate: 100,
    platformFeeRate: 10,
    includedItems: ["해녀 장비 일체 (웻슈트, 오리발, 물안경)", "해녀 선생님 동행", "직접 채취한 해산물", "조리 재료 및 강습"],
    excludedItems: ["추가 해산물 구매", "교통편"],
    refundPolicy: "3일 전 전액, 당일 50% (날씨·해황 취소 시 전액 환불)",
    hostName: "성산해녀문화원",
    hostRating: 5.0,
    hostPartyCount: 210,
    hostBio: "제주 해녀 문화 보존, 현직 해녀 선생님 직접 운영",
    tags: ["해녀체험", "성산", "해산물", "요리강습", "문화체험"],
    createdAt: "2026-04-23T09:00:00Z",
  },
  {
    id: "c5",
    partyType: "commercial",
    title: "제주 올레길 7코스 전동킥보드 투어",
    category: "cycling",
    description: "서귀포 올레길 7코스를 전동킥보드로 달리는 2.5시간 투어! 전문 가이드가 숨은 포토스팟을 안내하며, 보험과 안전 장비도 완비되어 있어요. 중간에 감성 카페 들러서 간식도 즐겨요.",
    date: "2026-06-01",
    time: "14:00",
    region: "서귀포",
    location: "서귀포 올레 7코스 시작점 (외돌개)",
    maxMembers: 8,
    currentMembers: 0,
    reservedSeats: 1,
    costType: "fixed",
    costAmount: 55000,
    hasRentalCar: false,
    operatorName: "제주이지투어",
    operatorContact: "010-3333-9999",
    operatorVerified: false,
    pricePerSeat: 55000,
    depositRate: 50,
    platformFeeRate: 10,
    minMembers: 2,
    includedItems: ["전동킥보드 대여 (2.5시간)", "안전모 및 보호대", "가이드 동행", "개인 사고 보험", "간식 1회"],
    excludedItems: ["카페 음료비 (개인 부담)", "주차비"],
    refundPolicy: "1일 전 전액, 당일 50%",
    stopSlugs: ["올레길-감성카페-d81aca"],
    hostName: "제주이지투어",
    hostRating: 4.7,
    hostPartyCount: 73,
    hostBio: "서귀포 전동킥보드 투어 전문, 안전 라이딩 가이드",
    tags: ["전동킥보드", "올레7코스", "서귀포", "투어", "보험포함"],
    schedule: [
      { time: "14:00", place: "외돌개 집합", memo: "장비 지급 및 안전 교육" },
      { time: "14:20", place: "올레 7코스 출발", memo: "가이드 선두" },
      { time: "15:20", place: "감성 카페", memo: "간식 타임 & 휴식" },
      { time: "15:50", place: "올레 7코스 계속", memo: "포토스팟 안내" },
      { time: "16:30", place: "월평포구 도착", memo: "투어 마무리" },
    ],
    createdAt: "2026-04-24T09:00:00Z",
  },

  // ── 번들 파티 (개인이 여러 활동 묶음) ────────────────────────────────────────
  {
    id: "b1",
    partyType: "individual",
    title: "협재 서핑 → 점심 흑돼지 → 한림 자전거 하루 코스",
    category: "surfing",
    description: "오전 협재 서핑 클래스, 점심 한림 흑돼지, 오후 자전거 번들 하루 코스예요. 렌트카 없으면 같이 렌트해요!",
    date: "2026-06-07",
    time: "09:00",
    region: "한림",
    location: "협재 해수욕장",
    maxMembers: 4,
    currentMembers: 1,
    costType: "split",
    costAmount: 120000,
    hasRentalCar: true,
    rentalCarMode: "rent-together",
    rentalCarPerPerson: 25000,
    rentalCarPickup: "제주공항",
    hostName: "파도러버준",
    hostRating: 4.8,
    hostPartyCount: 12,
    hostBio: "서핑 2년차. 협재 자주 가요.",
    tags: ["서핑", "자전거", "흑돼지", "한림", "번들", "렌트카공유"],
    rentalCoordEnabled: true,
    rentalCoordNote: "제주공항 09:00 출발, 차 1대 렌트 예정",
    rentalCoordSeats: 3,
    bundleItems: [
      {
        id: "bi-1",
        title: "협재 서핑 입문 클래스",
        category: "surfing",
        time: "09:30",
        location: "협재 해수욕장",
        cost: 65000,
        commercialPartyId: "c1",
        note: "제주웨이브서핑스쿨 (장비 포함)",
      },
      {
        id: "bi-2",
        title: "한림 흑돼지 점심",
        category: "food",
        time: "12:30",
        location: "한림읍 맛집 골목",
        cost: 18000,
        note: "1인 18,000원 내외",
      },
      {
        id: "bi-3",
        title: "한림공원 자전거",
        category: "cycling",
        time: "14:00",
        location: "한림공원 자전거 대여소",
        cost: 10000,
        note: "2시간 대여 기준",
      },
    ],
    schedule: [
      { time: "09:00", place: "제주공항 출발", memo: "렌트카 픽업" },
      { time: "09:30", place: "협재 해수욕장", memo: "서핑 클래스 2시간" },
      { time: "12:30", place: "한림 흑돼지 맛집", memo: "점심" },
      { time: "14:00", place: "한림공원", memo: "자전거 2시간" },
      { time: "16:30", place: "각자 이동", memo: "마무리" },
    ],
    createdAt: "2026-04-25T10:00:00Z",
  },
  {
    id: "b2",
    partyType: "individual",
    title: "성산 낚시 + 해산물 직화 + 우도 스노클링 2인 동행",
    category: "fishing",
    description: "성산 갯바위 낚시 → 직접 잡은 해산물 구워먹기 → 우도 페리 타고 스노클링까지. 차 있어서 픽업 가능해요. 조용히 제주 즐기고 싶은 분 환영!",
    date: "2026-06-14",
    time: "06:00",
    region: "성산",
    location: "성산 갯바위 (성산일출봉 인근)",
    maxMembers: 3,
    currentMembers: 1,
    costType: "split",
    costAmount: 80000,
    hasRentalCar: true,
    rentalCarMode: "own-car",
    hostName: "낚시좋아하는형",
    hostRating: 4.9,
    hostPartyCount: 7,
    hostBio: "낚시 5년. 차 있음. 조용한 동행 선호.",
    tags: ["낚시", "스노클링", "우도", "성산", "번들", "차있음"],
    rentalCoordEnabled: false,
    bundleItems: [
      {
        id: "bi-4",
        title: "성산 갯바위 낚시",
        category: "fishing",
        time: "06:00",
        location: "성산 갯바위",
        cost: 0,
        note: "낚싯대 여분 있어요",
      },
      {
        id: "bi-5",
        title: "해산물 직화 구이",
        category: "food",
        time: "10:00",
        location: "성산 해변",
        cost: 15000,
        note: "잡은 거 + 재료비 분담",
      },
      {
        id: "bi-6",
        title: "우도 스노클링",
        category: "diving",
        time: "13:00",
        location: "우도 하고수동",
        cost: 25000,
        note: "페리비 + 장비 대여 포함",
      },
    ],
    schedule: [
      { time: "06:00", place: "성산 갯바위", memo: "낚시 시작" },
      { time: "10:00", place: "해변", memo: "해산물 구이" },
      { time: "12:00", place: "성산포 여객터미널", memo: "우도 페리" },
      { time: "13:00", place: "우도 하고수동", memo: "스노클링 2시간" },
      { time: "16:00", place: "우도 카페", memo: "쉬다가 복귀" },
    ],
    createdAt: "2026-04-26T08:00:00Z",
  },

  // ── 한달살기 호스트 — 이미 제주 체류 중, 단기 동행 구함 ─────────────────
  {
    id: "s1",
    partyType: "individual",
    stayMode: "stay",
    title: "애월 한달살기 중 🐶 강아지랑 1박2일 같이 놀 사람",
    category: "other",
    description: "7월 한 달 애월에 머물고 있어요. 강아지 2마리(말티즈, 포메)랑 같이 사는 중인데, 주말에 1박2일 정도 같이 올레길 산책하고 바베큐 하실 분 구해요. 숙박은 거실 소파/에어매트 가능해요. 강아지 좋아하는 분이면 완벽.",
    date: "2026-07-12",
    time: "11:00",
    region: "애월",
    location: "애월읍 올레 16코스 인근",
    maxMembers: 3,
    currentMembers: 1,
    costType: "split",
    costAmount: 30000,
    hasRentalCar: false,
    hostStayDays: 31,
    hostStayRegion: "애월",
    guestNights: 1,
    guestCanStayOver: true,
    petFriendly: true,
    petTypes: ["강아지"],
    petRules: "강아지 동반 환영. 다견도 OK.",
    hostLocalTips: ["애월 단골 카페 알려드릴 수 있어요", "올레 16코스 숨은 포인트 알아요", "로컬 흑돼지 맛집 예약해드릴게요"],
    hostName: "제주살이준비중",
    hostRating: 4.9,
    hostPartyCount: 3,
    hostBio: "서울에서 재택근무 중. 7월 애월 한달살기 도전 중!",
    tags: ["한달살기", "애견동반", "애월", "1박2일", "올레길", "바베큐"],
    schedule: [
      { time: "11:00", place: "애월 집합", memo: "강아지 첫 만남" },
      { time: "12:00", place: "로컬 카페", memo: "단골 카페 투어" },
      { time: "15:00", place: "올레 16코스", memo: "강아지 산책 2시간" },
      { time: "18:00", place: "마당 바베큐", memo: "저녁 같이" },
      { time: "다음날 10:00", place: "애월 해변", memo: "아침 산책 후 해산" },
    ],
    createdAt: "2026-04-27T09:00:00Z",
  },
  {
    id: "s2",
    partyType: "individual",
    stayMode: "stay",
    title: "서귀포 3개월살기 중 😺 하루 같이 오션뷰 즐길 사람",
    category: "other",
    description: "서귀포 중문에서 3개월 살고 있어요. 고양이 2마리랑 같이 사는 중. 주말 하루 오션뷰 테라스에서 같이 커피 마시고, 올레 8코스 걷고, 서귀포 야시장 갈 사람 구해요. 숙박은 안 되지만 당일 동행은 언제든지 환영!",
    date: "2026-08-15",
    time: "10:00",
    region: "서귀포",
    location: "서귀포시 중문동",
    maxMembers: 3,
    currentMembers: 1,
    costType: "free",
    hasRentalCar: false,
    hostStayDays: 92,
    hostStayRegion: "서귀포",
    guestNights: 0,
    guestCanStayOver: false,
    petFriendly: true,
    petTypes: ["고양이", "강아지"],
    petRules: "고양이 집에서 만날 수 있어요. 방문 반려동물도 소형견 환영.",
    hostLocalTips: ["중문 숨은 해수욕장 알아요", "서귀포 야시장 꿀팁 있음", "오션뷰 카페 현지인 픽"],
    hostName: "냥집사이사장",
    hostRating: 5.0,
    hostPartyCount: 1,
    hostBio: "프리랜서 디자이너. 고양이 2마리. 서귀포 3개월살기 중.",
    tags: ["3개월살기", "고양이", "오션뷰", "서귀포", "당일동행", "올레8코스"],
    rentalCoordEnabled: true,
    rentalCoordNote: "제가 차 있어서 중문 일대는 태워드릴 수 있어요",
    rentalCoordSeats: 2,
    schedule: [
      { time: "10:00", place: "테라스 커피", memo: "오션뷰 브런치" },
      { time: "12:00", place: "올레 8코스", memo: "2시간 트레킹" },
      { time: "15:00", place: "중문 카페", memo: "쉬다가" },
      { time: "18:00", place: "서귀포 야시장", memo: "저녁 먹고 해산" },
    ],
    createdAt: "2026-04-28T10:00:00Z",
  },
  {
    id: "s3",
    partyType: "individual",
    stayMode: "stay",
    title: "성산 2주살기 🌊 낚시 + 일출봉 같이 갈 1-2명",
    category: "fishing",
    description: "성산에서 2주 살고 있어요. 강아지(진돗개)랑 같이 와 있는데 낚시 좋아하는 분이면 같이 갯바위 가요. 일출봉 새벽 등반도 같이 하면 좋고. 숙박은 근처 게스트하우스 추천드릴게요. 차로 픽업도 가능.",
    date: "2026-06-20",
    time: "05:30",
    region: "성산",
    location: "성산 갯바위",
    maxMembers: 2,
    currentMembers: 1,
    costType: "split",
    costAmount: 20000,
    hasRentalCar: true,
    rentalCarMode: "own-car",
    hostStayDays: 14,
    hostStayRegion: "성산",
    guestNights: 0,
    guestCanStayOver: false,
    petFriendly: true,
    petTypes: ["강아지"],
    petRules: "진돗개 1마리 있어요. 다른 강아지도 OK.",
    hostLocalTips: ["성산 갯바위 포인트 알아요", "새벽 일출봉 덜 붐비는 시간 알아요", "성산 로컬 밥집 픽"],
    hostName: "낚시좋아하는형",
    hostRating: 4.9,
    hostPartyCount: 7,
    hostBio: "낚시 5년. 성산 2주 살기 중. 차 있음.",
    tags: ["2주살기", "낚시", "성산", "일출봉", "강아지", "픽업가능"],
    schedule: [
      { time: "05:30", place: "성산 갯바위", memo: "새벽 낚시" },
      { time: "09:00", place: "성산일출봉", memo: "등반 (선택)" },
      { time: "11:00", place: "로컬 밥집", memo: "아침 겸 점심" },
    ],
    createdAt: "2026-04-29T09:00:00Z",
  },
];
