import { FishingClub } from "./types";

export const DUMMY_GATHERINGS: FishingClub[] = [
  {
    id: "g1",
    name: "애월낚시동우회",
    region: "애월",
    specialty: "감성돔·농어",
    memberCount: 28,
    maxMembers: 35,
    meetingFrequency: "매주 토요일",
    level: "전체",
    fishTypes: ["감성돔", "농어", "벵에돔"],
    activities: ["정기 갯바위 출조", "초보자 강습", "연말 대회"],
    description: "애월 해안을 중심으로 매주 토요일 정기 출조하는 동우회입니다. 입문자도 환영하며 선배 회원들이 채비와 포인트를 친절히 안내해 드립니다. 월 1회 전체 회식도 있어요.",
    monthlyFee: 10000,
    nextOuting: "2026-05-17",
    openRecruiting: true,
    createdAt: "2024-03-01T09:00:00Z",
  },
  {
    id: "g2",
    name: "제주바다낚시클럽",
    region: "제주시",
    specialty: "방어·부시리 지깅",
    memberCount: 42,
    maxMembers: 50,
    meetingFrequency: "격주 일요일",
    level: "중급",
    fishTypes: ["방어", "부시리", "삼치"],
    activities: ["선상 지깅 원정", "메탈지그 공구", "방어 대회"],
    description: "선상 루어·지깅 전문 클럽입니다. 격주 일요일에 모슬포·성산에서 선박을 대절해 방어와 부시리를 노립니다. 중급 이상 경험자 중심이며 루어 공구와 장비 정보 공유도 활발합니다.",
    monthlyFee: 20000,
    nextOuting: "2026-05-18",
    openRecruiting: true,
    createdAt: "2023-08-15T10:00:00Z",
  },
  {
    id: "g3",
    name: "서귀포갯바위클럽",
    region: "서귀포",
    specialty: "돌돔·벵에돔",
    memberCount: 19,
    maxMembers: 20,
    meetingFrequency: "매주 일요일",
    level: "고급",
    fishTypes: ["돌돔", "벵에돔", "감성돔"],
    activities: ["문섬·범섬 원정", "돌돔 대회", "채비 클래스"],
    description: "서귀포 문섬·범섬 갯바위를 주무대로 하는 고급 낚시 동호회입니다. 원줄 4호 이상 세팅이 필수이며 도선을 이용한 원정 출조 위주입니다. 조황 정보와 포인트 노하우를 회원 간 공유합니다.",
    monthlyFee: 15000,
    nextOuting: "2026-05-19",
    openRecruiting: false,
    createdAt: "2022-05-10T08:00:00Z",
  },
  {
    id: "g4",
    name: "한림볼락루어동호회",
    region: "한림",
    specialty: "볼락·전갱이 라이트루어",
    memberCount: 31,
    maxMembers: 40,
    meetingFrequency: "매주 금요일 야간",
    level: "입문",
    fishTypes: ["볼락", "전갱이", "학공치"],
    activities: ["야간 볼락 루어", "초보자 강습", "웜·지그헤드 공구"],
    description: "한림항과 협재 방파제를 중심으로 매주 금요일 밤 야간 볼락 루어를 즐기는 동호회입니다. 라이트 루어대와 2g 지그헤드 세팅이면 충분합니다. 입문자 환영, 채비 방법부터 함께 배워요.",
    monthlyFee: 0,
    nextOuting: "2026-05-16",
    openRecruiting: true,
    createdAt: "2024-01-20T18:00:00Z",
  },
  {
    id: "g5",
    name: "성산일출낚시회",
    region: "성산",
    specialty: "참돔·방어 선상",
    memberCount: 24,
    maxMembers: 30,
    meetingFrequency: "월 2회 토요일",
    level: "중급",
    fishTypes: ["참돔", "방어", "반열기"],
    activities: ["일출 선상 출조", "참돔 타이라바", "회식 및 교류"],
    description: "성산 일출을 감상하며 참돔과 방어를 노리는 선상 낚시 클럽입니다. 월 2회 성산포항에서 미니선을 대절해 출항합니다. 타이라바·메탈지그 위주이며 경험 공유와 조황 정보 교류가 활발합니다.",
    monthlyFee: 15000,
    nextOuting: "2026-05-24",
    openRecruiting: true,
    createdAt: "2023-04-01T05:00:00Z",
  },
  {
    id: "g6",
    name: "제주낚시입문학교",
    region: "제주시",
    specialty: "방파제 체험·찌낚시",
    memberCount: 55,
    maxMembers: 80,
    meetingFrequency: "매주 토·일",
    level: "입문",
    fishTypes: ["전갱이", "볼락", "감성돔"],
    activities: ["왕초보 강습", "가족 낚시 체험", "어린이 낚시 교실"],
    description: "낚시를 처음 접하는 분들을 위한 입문 동아리입니다. 제주시 이호테우·건입동 방파제에서 매주 주말에 모입니다. 찌 맞춤부터 미끼 달기까지 기초를 가르쳐 드립니다. 어린이와 가족 참여 환영합니다.",
    monthlyFee: 0,
    nextOuting: "2026-05-17",
    openRecruiting: true,
    createdAt: "2024-06-01T09:00:00Z",
  },
  {
    id: "g7",
    name: "모슬포원정대",
    region: "모슬포",
    specialty: "야간 갈치·방어 지깅",
    memberCount: 18,
    maxMembers: 25,
    meetingFrequency: "매주 수요일 야간",
    level: "중급",
    fishTypes: ["갈치", "방어", "부시리"],
    activities: ["야간 갈치 선상", "방어 지깅 원정", "어획물 나눔"],
    description: "모슬포항을 거점으로 야간 갈치 선상과 방어 지깅을 즐기는 클럽입니다. 매주 수요일 야간에 출항하며 회원 전용 할인 선박을 이용합니다. 잡은 생선은 함께 나눠 가져갑니다.",
    monthlyFee: 10000,
    nextOuting: "2026-05-20",
    openRecruiting: true,
    createdAt: "2023-11-05T16:00:00Z",
  },
  {
    id: "g8",
    name: "구좌바다탐험대",
    region: "구좌",
    specialty: "돌돔·감성돔 갯바위",
    memberCount: 14,
    maxMembers: 20,
    meetingFrequency: "격주 토요일",
    level: "고급",
    fishTypes: ["돌돔", "감성돔", "벵에돔"],
    activities: ["세화리 갯바위 출조", "성게 미끼 공동 구매", "조황 대회"],
    description: "구좌 세화리·종달리 갯바위를 주무대로 하는 고급 찌낚시 동호회입니다. 원줄 4호 이상 세팅이 필수이며 성게 미끼를 공동 구매해 비용을 절감합니다. 조황 사진과 포인트 정보를 회원 간 적극 공유합니다.",
    monthlyFee: 12000,
    nextOuting: "2026-05-22",
    openRecruiting: false,
    createdAt: "2022-09-15T06:00:00Z",
  },
];
