import { CatchReport } from "./types";

export const DUMMY_CATCHES: CatchReport[] = [
  {
    id: "cr1", authorName: "서귀포갯바위왕", authorLevel: "고수",
    location: "서귀포 법환포구 북방파제 끝", region: "서귀포", spotType: "방파제", fishingMethod: "찌낚시",
    catches: [
      { fishName: "감성돔", size: "42cm", count: 2, note: "크릴 반마리에 히트" },
      { fishName: "벵에돔", size: "28cm", count: 5 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.3m", temp: 19 },
    tidePhase: "7물", rating: 5,
    content: "오전 7시 입질 시작. 조류가 우측으로 흐를 때 입질 집중. 원줄 3호 목줄 2호 G2찌 세팅. 법환포구 북쪽 끝 테트라포드 사이에서 연속 히트. 벵에돔은 표층 30cm 이내에서 올라왔고 감성돔은 1.5m 층에서 입질.",
    tags: ["감성돔", "벵에돔", "찌낚시", "법환포구", "7물"], likeCount: 47, commentCount: 12, createdAt: "2026-05-10T08:30:00Z",
  },
  {
    id: "cr2", authorName: "루어마스터최", authorLevel: "프로",
    location: "성산 오조리 갯바위", region: "성산", spotType: "갯바위", fishingMethod: "루어",
    catches: [
      { fishName: "부시리", size: "78cm", count: 1, note: "팝퍼 표층 작업" },
      { fishName: "방어", size: "62cm", count: 3 },
    ],
    weather: { condition: "흐림", windSpeed: "5~7m/s", waveHeight: "0.8m", temp: 16 },
    tidePhase: "12물", rating: 5,
    content: "바람이 좀 있었지만 파도 때문에 오히려 포인트 앞에서 베이트(전갱이 무리)가 쏠렸음. 팝퍼로 수면 작업 중 78cm 부시리 선두. 방어 3마리 추가. 메탈지그 80g으로 바닥층 탐색 시 방어 두 마리 추가.",
    tags: ["부시리", "방어", "루어", "갯바위", "성산"], likeCount: 89, commentCount: 23, createdAt: "2026-05-09T16:20:00Z",
  },
  {
    id: "cr3", authorName: "한림낚시왕", authorLevel: "고수",
    location: "한림항 방파제 내항", region: "한림", spotType: "방파제", fishingMethod: "생미끼",
    catches: [
      { fishName: "볼락", size: "22cm", count: 12 },
      { fishName: "전갱이", size: "25cm", count: 8 },
    ],
    weather: { condition: "맑음", windSpeed: "1~2m/s", waveHeight: "0.2m", temp: 21 },
    tidePhase: "3물", rating: 4,
    content: "야간 8시~자정. 방파제 내항 쪽에 볼락 엄청 많음. 수중찌 0.5호에 크릴 세팅. 전갱이는 카고채비로 중층 공략. 가족이랑 같이 와서 재밌게 놀았어요.",
    tags: ["볼락", "전갱이", "야간", "한림", "가족낚시"], likeCount: 31, commentCount: 8, createdAt: "2026-05-09T23:45:00Z",
  },
  {
    id: "cr4", authorName: "좌대매니아", authorLevel: "중급",
    location: "서귀포 황금좌대", region: "서귀포", spotType: "좌대", fishingMethod: "좌대낚시",
    catches: [
      { fishName: "참돔", size: "51cm", count: 1 },
      { fishName: "감성돔", size: "38cm", count: 2 },
      { fishName: "벵에돔", size: "30cm", count: 4 },
    ],
    weather: { condition: "맑음", windSpeed: "3~5m/s", waveHeight: "0.5m", temp: 18 },
    tidePhase: "8물", rating: 5,
    content: "오전 5시부터 오후 3시까지. 참돔 51cm 대박! 좌대 직원분이 수심과 미끼 세팅 도와줘서 초반에 좋았음. 감성돔은 새벽 6~7시 집중 입질. 시설도 깔끔하고 정말 추천합니다.",
    tags: ["참돔", "감성돔", "좌대", "서귀포", "황금좌대"], likeCount: 63, commentCount: 17, createdAt: "2026-05-08T15:00:00Z",
  },
  {
    id: "cr5", authorName: "선상고수박", authorLevel: "프로",
    location: "성산포항 출발 선상", region: "성산", spotType: "선상", fishingMethod: "선상",
    catches: [
      { fishName: "방어", size: "75cm", count: 2 },
      { fishName: "삼치", size: "85cm", count: 1 },
      { fishName: "부시리", size: "90cm", count: 1, note: "대박 사이즈" },
    ],
    weather: { condition: "맑음", windSpeed: "4~6m/s", waveHeight: "0.6m", temp: 15 },
    tidePhase: "11물", rating: 5,
    content: "성산 앞바다 선상. 90cm 부시리 대박. 지깅 200g 메탈지그로 바닥층 탐색 중 히트. 방어·삼치·부시리 한 배에서 올인. 최고의 하루.",
    tags: ["방어", "삼치", "부시리", "선상", "성산", "지깅"], likeCount: 142, commentCount: 38, createdAt: "2026-05-07T17:30:00Z",
  },
  {
    id: "cr6", authorName: "애월꾼", authorLevel: "중급",
    location: "애월 고내포구 방파제", region: "애월", spotType: "방파제", fishingMethod: "원투",
    catches: [
      { fishName: "넙치", size: "45cm", count: 1 },
      { fishName: "볼락", size: "20cm", count: 6 },
    ],
    weather: { condition: "흐림", windSpeed: "6~8m/s", waveHeight: "0.7m", temp: 17 },
    tidePhase: "5물", rating: 3,
    content: "바람이 많이 불어서 원투하기 좋은 날씨는 아니었지만 넙치 한 마리는 건졌어요. 생미끼 참갯지렁이로 원투. 볼락은 방파제 끝 테트라 틈에서 루어로 뽑았습니다.",
    tags: ["넙치", "볼락", "원투", "애월", "고내포구"], likeCount: 22, commentCount: 5, createdAt: "2026-05-07T11:00:00Z",
  },
  {
    id: "cr7", authorName: "구좌낚시러버", authorLevel: "고수",
    location: "구좌 세화리 갯바위", region: "구좌", spotType: "갯바위", fishingMethod: "찌낚시",
    catches: [
      { fishName: "돌돔", size: "38cm", count: 1 },
      { fishName: "감성돔", size: "44cm", count: 1 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.4m", temp: 20 },
    tidePhase: "9물", rating: 5,
    content: "세화리 갯바위 명포인트. 돌돔 38cm 구좌에서 처음 올렸어요! 원줄 4호 목줄 3호 굵게 세팅. 성게 미끼로 포인트 공략. 감성돔도 추가로 대만족.",
    tags: ["돌돔", "감성돔", "갯바위", "구좌", "세화리"], likeCount: 55, commentCount: 14, createdAt: "2026-05-06T10:00:00Z",
  },
  {
    id: "cr8", authorName: "초보탈출중", authorLevel: "초보",
    location: "제주시 이호테우해변 방파제", region: "제주시", spotType: "방파제", fishingMethod: "생미끼",
    catches: [
      { fishName: "전갱이", size: "20cm", count: 15 },
      { fishName: "학공치", size: "35cm", count: 3 },
    ],
    weather: { condition: "맑음", windSpeed: "3~4m/s", waveHeight: "0.3m", temp: 22 },
    tidePhase: "6물", rating: 4,
    content: "첫 낚시 치고 대박이에요! 동네 아저씨가 카고채비 세팅 도와주셔서 전갱이 15마리. 학공치도 잡았어요. 회는 못 치겠고 구워먹었는데 맛있었습니다 ㅎㅎ",
    tags: ["전갱이", "학공치", "초보", "이호테우", "제주시"], likeCount: 28, commentCount: 19, createdAt: "2026-05-05T14:00:00Z",
  },
  {
    id: "cr9", authorName: "모슬포방어헌터", authorLevel: "프로",
    location: "모슬포항 앞바다 선상", region: "모슬포", spotType: "선상", fishingMethod: "루어",
    catches: [
      { fishName: "방어", size: "82cm", count: 1 },
      { fishName: "방어", size: "67cm", count: 2 },
    ],
    weather: { condition: "맑음", windSpeed: "4~5m/s", waveHeight: "0.5m", temp: 14 },
    tidePhase: "14물", rating: 5,
    content: "모슬포 앞바다 방어 시즌 마무리 직전. 150g 메탈지그 수직지깅으로 바닥층 공략. 82cm 방어 첫 히트에 30분 파이팅. 회 떠서 배에서 먹었어요 😂",
    tags: ["방어", "모슬포", "선상", "지깅", "루어"], likeCount: 107, commentCount: 29, createdAt: "2026-05-04T18:00:00Z",
  },
  {
    id: "cr10", authorName: "한림갯바위집사", authorLevel: "고수",
    location: "한림 협재 갯바위", region: "한림", spotType: "갯바위", fishingMethod: "찌낚시",
    catches: [
      { fishName: "벵에돔", size: "33cm", count: 7 },
      { fishName: "참돔", size: "29cm", count: 2 },
    ],
    weather: { condition: "맑음", windSpeed: "1~2m/s", waveHeight: "0.2m", temp: 20 },
    tidePhase: "2물", rating: 4,
    content: "협재 앞 갯바위 벵에돔 시즌 돌입했어요. 2물이라 조류 약해서 좀 아쉬웠지만 밑밥 3시간 뿌린 보람 있음. 벵에돔 7마리, 참돔 2마리로 마무리.",
    tags: ["벵에돔", "참돔", "협재", "한림", "찌낚시"], likeCount: 44, commentCount: 11, createdAt: "2026-05-03T09:00:00Z",
  },
  {
    id: "cr11", authorName: "성산일출낚시꾼", authorLevel: "중급",
    location: "성산 일출봉 주변 방파제", region: "성산", spotType: "방파제", fishingMethod: "루어",
    catches: [
      { fishName: "농어", size: "52cm", count: 1 },
      { fishName: "볼락", size: "24cm", count: 4 },
    ],
    weather: { condition: "흐림", windSpeed: "4~6m/s", waveHeight: "0.6m", temp: 18 },
    tidePhase: "10물", rating: 4,
    content: "일출봉 옆 방파제에서 농어 52cm! 미노우 루어로 표층 작업 중 히트. 볼락은 소프트 베이트로 테트라 틈 탐색.",
    tags: ["농어", "볼락", "루어", "성산", "일출봉"], likeCount: 36, commentCount: 9, createdAt: "2026-05-02T17:00:00Z",
  },
  {
    id: "cr12", authorName: "우도선상러버", authorLevel: "고수",
    location: "우도 주변 선상", region: "우도", spotType: "선상", fishingMethod: "선상",
    catches: [
      { fishName: "반열기", size: "35cm", count: 6 },
      { fishName: "참돔", size: "42cm", count: 2 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.3m", temp: 21 },
    tidePhase: "6물", rating: 5,
    content: "우도 주변 제주 명물 반열기 작업. 생새우 미끼로 바닥층 공략. 반열기 빨간색이 정말 예쁘더라고요. 참돔도 추가. 우도 선상 강추!",
    tags: ["반열기", "참돔", "선상", "우도"], likeCount: 78, commentCount: 20, createdAt: "2026-05-01T16:00:00Z",
  },
  {
    id: "cr13", authorName: "서귀포새벽꾼", authorLevel: "프로",
    location: "서귀포 외돌개 갯바위", region: "서귀포", spotType: "갯바위", fishingMethod: "찌낚시",
    catches: [
      { fishName: "감성돔", size: "48cm", count: 1 },
      { fishName: "감성돔", size: "39cm", count: 2 },
    ],
    weather: { condition: "맑음", windSpeed: "1~2m/s", waveHeight: "0.2m", temp: 17 },
    tidePhase: "8물", rating: 5,
    content: "외돌개 새벽 4시 포인트 확보. 8물 조류 딱 맞아서 입질 폭발. 감성돔 48cm 포함 3마리. 날씨 완벽. 외돌개는 새벽이 진짜.",
    tags: ["감성돔", "외돌개", "서귀포", "새벽낚시"], likeCount: 91, commentCount: 26, createdAt: "2026-04-30T05:00:00Z",
  },
  {
    id: "cr14", authorName: "구좌볼락헌터", authorLevel: "중급",
    location: "구좌 종달리 방파제", region: "구좌", spotType: "방파제", fishingMethod: "루어",
    catches: [
      { fishName: "볼락", size: "26cm", count: 20 },
      { fishName: "쥐치", size: "22cm", count: 5 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.3m", temp: 19 },
    tidePhase: "4물", rating: 4,
    content: "종달리 야간 볼락 대박. 2g 지그헤드에 1.5인치 웜으로 방파제 외벽 탐색. 볼락 20마리는 이번 시즌 최고 기록!",
    tags: ["볼락", "야간", "루어", "구좌", "종달리"], likeCount: 53, commentCount: 15, createdAt: "2026-04-29T21:00:00Z",
  },
  {
    id: "cr15", authorName: "애월감성꾼", authorLevel: "고수",
    location: "애월 애월포구 방파제", region: "애월", spotType: "방파제", fishingMethod: "찌낚시",
    catches: [
      { fishName: "감성돔", size: "40cm", count: 3 },
    ],
    weather: { condition: "흐림", windSpeed: "3~5m/s", waveHeight: "0.5m", temp: 18 },
    tidePhase: "11물", rating: 4,
    content: "애월포구 내항 방파제. 흐린 날이 감성돔 입질 더 좋음. 원줄 2.5호 목줄 1.7호 0찌. 크릴+밑밥 3시간 뿌려준 보람. 40cm급 3마리로 마무리.",
    tags: ["감성돔", "애월", "찌낚시", "흐린날"], likeCount: 41, commentCount: 10, createdAt: "2026-04-28T11:00:00Z",
  },
  {
    id: "cr16", authorName: "한림좌대단골", authorLevel: "중급",
    location: "한림 비양도 좌대", region: "한림", spotType: "좌대", fishingMethod: "좌대낚시",
    catches: [
      { fishName: "참돔", size: "45cm", count: 2 },
      { fishName: "벵에돔", size: "32cm", count: 5 },
      { fishName: "볼락", size: "23cm", count: 8 },
    ],
    weather: { condition: "맑음", windSpeed: "2~4m/s", waveHeight: "0.4m", temp: 20 },
    tidePhase: "6물", rating: 5,
    content: "비양도 좌대 최고! 참돔 45cm 두 마리는 정말 기분 좋았어요. 미끼는 생새우로 바닥층 2m 공략. 볼락은 표층에서 잡았어요.",
    tags: ["참돔", "벵에돔", "볼락", "한림", "비양도", "좌대"], likeCount: 67, commentCount: 18, createdAt: "2026-04-27T15:00:00Z",
  },
  {
    id: "cr17", authorName: "제주시야간꾼", authorLevel: "중급",
    location: "제주시 삼양 검은모래해변 방파제", region: "제주시", spotType: "방파제", fishingMethod: "원투",
    catches: [
      { fishName: "넙치", size: "55cm", count: 1, note: "야간 원투 대박" },
      { fishName: "볼락", size: "21cm", count: 9 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.3m", temp: 16 },
    tidePhase: "7물", rating: 5,
    content: "야간 원투로 55cm 넙치 첫 경험! 갯지렁이+크릴 합사 미끼로 원투. 볼락은 방파제 내항 소프트베이트로.",
    tags: ["넙치", "볼락", "야간", "원투", "삼양", "제주시"], likeCount: 48, commentCount: 13, createdAt: "2026-04-26T22:00:00Z",
  },
  {
    id: "cr18", authorName: "성산바다사나이", authorLevel: "고수",
    location: "성산 신산리 갯바위", region: "성산", spotType: "갯바위", fishingMethod: "찌낚시",
    catches: [
      { fishName: "돌돔", size: "42cm", count: 1 },
      { fishName: "벵에돔", size: "35cm", count: 3 },
    ],
    weather: { condition: "맑음", windSpeed: "3~4m/s", waveHeight: "0.4m", temp: 19 },
    tidePhase: "9물", rating: 5,
    content: "신산리 갯바위 돌돔 포인트. 성게 미끼로 돌돔 42cm 획득! 이 포인트는 9~11물이 최고. 벵에돔도 중간층에서 3마리.",
    tags: ["돌돔", "벵에돔", "성산", "갯바위", "성게미끼"], likeCount: 72, commentCount: 19, createdAt: "2026-04-25T10:00:00Z",
  },
  {
    id: "cr19", authorName: "모슬포선상박사", authorLevel: "프로",
    location: "모슬포 앞바다 좌대", region: "모슬포", spotType: "좌대", fishingMethod: "좌대낚시",
    catches: [
      { fishName: "참돔", size: "58cm", count: 1, note: "시즌 최대어" },
      { fishName: "참돔", size: "44cm", count: 3 },
    ],
    weather: { condition: "맑음", windSpeed: "1~2m/s", waveHeight: "0.2m", temp: 18 },
    tidePhase: "5물", rating: 5,
    content: "모슬포 방어좌대에서 참돔으로 변경. 58cm 시즌 최대어 나왔어요. 5물 고요한 바다에서 바닥층 생새우 미끼. 진짜 명당.",
    tags: ["참돔", "모슬포", "좌대", "대형어"], likeCount: 118, commentCount: 32, createdAt: "2026-04-24T14:00:00Z",
  },
  {
    id: "cr20", authorName: "애월루어꾼", authorLevel: "중급",
    location: "애월 수산리 갯바위", region: "애월", spotType: "갯바위", fishingMethod: "루어",
    catches: [
      { fishName: "농어", size: "60cm", count: 1 },
      { fishName: "부시리", size: "55cm", count: 1 },
    ],
    weather: { condition: "흐림", windSpeed: "5~7m/s", waveHeight: "0.7m", temp: 17 },
    tidePhase: "13물", rating: 4,
    content: "수산리 갯바위 루어. 농어 60cm 미노우 히트, 부시리 55cm 메탈지그. 바람 많이 불어서 캐스팅 힘들었지만 결과는 대박!",
    tags: ["농어", "부시리", "애월", "갯바위", "루어"], likeCount: 39, commentCount: 11, createdAt: "2026-04-23T16:00:00Z",
  },
  {
    id: "cr21", authorName: "구좌해녀아들", authorLevel: "고수",
    location: "구좌 하도리 해안", region: "구좌", spotType: "해안", fishingMethod: "생미끼",
    catches: [
      { fishName: "쏨뱅이", size: "28cm", count: 3 },
      { fishName: "볼락", size: "22cm", count: 6 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.3m", temp: 21 },
    tidePhase: "4물", rating: 3,
    content: "하도리 해안가 수중여 포인트. 쏨뱅이 특유의 바닥 붙는 습성 때문에 바닥층 1m 공략. 독이 있으니 조심.",
    tags: ["쏨뱅이", "볼락", "구좌", "해안", "수중여"], likeCount: 24, commentCount: 7, createdAt: "2026-04-22T13:00:00Z",
  },
  {
    id: "cr22", authorName: "서귀포대물꾼", authorLevel: "프로",
    location: "서귀포 문섬 갯바위 도선", region: "서귀포", spotType: "갯바위", fishingMethod: "찌낚시",
    catches: [
      { fishName: "벵에돔", size: "40cm", count: 1, note: "준척급" },
      { fishName: "벵에돔", size: "35cm", count: 4 },
      { fishName: "감성돔", size: "46cm", count: 1 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.4m", temp: 19 },
    tidePhase: "7물", rating: 5,
    content: "문섬 도선 이용 갯바위. 벵에돔 5마리 + 감성돔 1마리. 문섬은 진짜 레전드 포인트. 도선비 35,000원이지만 충분히 가치 있음. 원줄 2.5호 목줄 1.5호 B찌.",
    tags: ["벵에돔", "감성돔", "문섬", "서귀포", "도선", "갯바위"], likeCount: 95, commentCount: 28, createdAt: "2026-04-21T09:00:00Z",
  },
  {
    id: "cr23", authorName: "성산학공치헌터", authorLevel: "중급",
    location: "성산 성산포구 방파제", region: "성산", spotType: "방파제", fishingMethod: "생미끼",
    catches: [
      { fishName: "학공치", size: "40cm", count: 18 },
      { fishName: "전갱이", size: "28cm", count: 5 },
    ],
    weather: { condition: "맑음", windSpeed: "3~4m/s", waveHeight: "0.3m", temp: 20 },
    tidePhase: "6물", rating: 4,
    content: "성산 학공치 시즌! 방파제 끝에서 카고채비로 18마리. 회 떠먹으니 담백하고 맛있어요. 아이들이랑 와도 좋을 듯.",
    tags: ["학공치", "전갱이", "성산", "방파제", "초보환영"], likeCount: 33, commentCount: 9, createdAt: "2026-04-20T13:00:00Z",
  },
  {
    id: "cr24", authorName: "한림선상왕", authorLevel: "고수",
    location: "한림항 출발 선상", region: "한림", spotType: "선상", fishingMethod: "선상",
    catches: [
      { fishName: "갈치", size: "F3지", count: 15, note: "태백어 성급 수준" },
    ],
    weather: { condition: "흐림", windSpeed: "4~5m/s", waveHeight: "0.6m", temp: 16 },
    tidePhase: "10물", rating: 5,
    content: "한림 갈치 선상. F3지 15마리 대박! 전동릴에 갈치용 루어(일명 갈치커터) 사용. 야간 조명에 갈치 떼 모이는 거 장관. 회·구이 모두 최고.",
    tags: ["갈치", "한림", "선상", "야간", "전동릴"], likeCount: 61, commentCount: 22, createdAt: "2026-04-19T20:00:00Z",
  },
  {
    id: "cr25", authorName: "제주시낚시초보", authorLevel: "초보",
    location: "제주시 탑동 방파제", region: "제주시", spotType: "방파제", fishingMethod: "생미끼",
    catches: [
      { fishName: "전갱이", size: "22cm", count: 8 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.2m", temp: 23 },
    tidePhase: "5물", rating: 3,
    content: "탑동 방파제 초보 도전. 카고채비 처음 써봤는데 생각보다 어렵지 않아요. 전갱이 8마리 잡아서 뿌듯. 다음엔 감성돔 도전해볼게요!",
    tags: ["전갱이", "초보", "제주시", "탑동"], likeCount: 15, commentCount: 11, createdAt: "2026-04-18T14:00:00Z",
  },
  {
    id: "cr26", authorName: "서귀포겨울낚시꾼", authorLevel: "고수",
    location: "서귀포 강정포구 방파제", region: "서귀포", spotType: "방파제", fishingMethod: "찌낚시",
    catches: [
      { fishName: "감성돔", size: "50cm", count: 1, note: "50cm 돌파!" },
      { fishName: "감성돔", size: "37cm", count: 2 },
    ],
    weather: { condition: "흐림", windSpeed: "5~6m/s", waveHeight: "0.6m", temp: 15 },
    tidePhase: "12물", rating: 5,
    content: "강정 방파제 새벽 감성돔 도전. 50cm 넘으니까 파이팅이 장난 아니에요. 12물 조류 센 날 입질 집중. 원줄 3호 목줄 2.5호 필수.",
    tags: ["감성돔", "50cm", "강정", "서귀포", "찌낚시"], likeCount: 83, commentCount: 24, createdAt: "2026-04-17T06:00:00Z",
  },
  {
    id: "cr27", authorName: "모슬포갈치선장", authorLevel: "프로",
    location: "모슬포항 야간 선상", region: "모슬포", spotType: "선상", fishingMethod: "선상",
    catches: [
      { fishName: "갈치", size: "F4지", count: 20 },
    ],
    weather: { condition: "맑음", windSpeed: "1~2m/s", waveHeight: "0.2m", temp: 14 },
    tidePhase: "7물", rating: 5,
    content: "모슬포 야간 갈치 선상. F4지 갈치 20마리. 동생이 처음 낚시 왔는데 전동릴 달아줬더니 혼자 12마리나 잡음 ㅋㅋ 조황 진짜 최고.",
    tags: ["갈치", "모슬포", "야간", "선상", "F4지"], likeCount: 99, commentCount: 31, createdAt: "2026-04-16T23:00:00Z",
  },
  {
    id: "cr28", authorName: "우도펜션낚시", authorLevel: "초보",
    location: "우도 하고수동 방파제", region: "우도", spotType: "방파제", fishingMethod: "생미끼",
    catches: [
      { fishName: "볼락", size: "18cm", count: 7 },
      { fishName: "전갱이", size: "21cm", count: 10 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.3m", temp: 22 },
    tidePhase: "3물", rating: 4,
    content: "우도 여행 중 숙소 앞 방파제에서 낚시. 볼락이랑 전갱이 엄청 잡혔어요! 우도 여행 가시는 분들 낚시대 한 개 들고 가세요.",
    tags: ["볼락", "전갱이", "우도", "초보", "방파제"], likeCount: 26, commentCount: 14, createdAt: "2026-04-15T16:00:00Z",
  },
  {
    id: "cr29", authorName: "애월선상갈치꾼", authorLevel: "중급",
    location: "애월항 야간 선상 갈치", region: "애월", spotType: "선상", fishingMethod: "선상",
    catches: [
      { fishName: "갈치", size: "F3지", count: 12 },
      { fishName: "전갱이", size: "30cm", count: 5 },
    ],
    weather: { condition: "맑음", windSpeed: "2~3m/s", waveHeight: "0.3m", temp: 18 },
    tidePhase: "8물", rating: 4,
    content: "애월 야간 갈치 선상. 12마리에 전갱이 보너스. 선장님 포인트 잘 잡아주셔서 입질 폭발. 갈치 조림용으로 가져갔어요.",
    tags: ["갈치", "전갱이", "애월", "야간", "선상"], likeCount: 37, commentCount: 10, createdAt: "2026-04-14T21:00:00Z",
  },
  {
    id: "cr30", authorName: "서귀포참돔박사", authorLevel: "프로",
    location: "서귀포 범섬 주변 선상", region: "서귀포", spotType: "선상", fishingMethod: "선상",
    catches: [
      { fishName: "참돔", size: "65cm", count: 1, note: "대형 참돔" },
      { fishName: "참돔", size: "48cm", count: 2 },
      { fishName: "반열기", size: "40cm", count: 3 },
    ],
    weather: { condition: "맑음", windSpeed: "2~4m/s", waveHeight: "0.4m", temp: 18 },
    tidePhase: "9물", rating: 5,
    content: "범섬 주변 참돔 지깅. 65cm 참돔 큰 놈 나왔어요!! 코 찌르는 향 나는 살아있는 새우 미끼 최강. 반열기는 보너스. 서귀포 범섬은 참돔 성지.",
    tags: ["참돔", "반열기", "서귀포", "범섬", "선상", "대형어"], likeCount: 154, commentCount: 45, createdAt: "2026-04-13T17:00:00Z",
  },
];
