import { Jwaedae } from "./types";

export const DUMMY_JWAEDAE: Jwaedae[] = [
  {
    id: "jw1", name: "서귀포 황금좌대", region: "서귀포",
    location: "서귀포시 법환동 앞바다 1.2km", operatorName: "황금수산", operatorPhone: "064-732-0001",
    description: "서귀포 최대 규모 좌대. 30인 수용 가능. 취사 가능, 숙박형 패키지 운영. 참돔·감성돔·벵에돔 시즌 조황 우수. 낚시 초보자도 직원 가이드 서비스 제공.",
    targetFish: ["참돔", "감성돔", "벵에돔", "볼락"],
    facilities: ["낚시대 대여", "생미끼 제공", "화장실", "취사 가능", "숙박", "샤워시설", "WiFi"],
    priceDay: 55000, priceNight: 80000, capacity: 30, availableSeats: 8,
    rating: 4.8, reviewCount: 142, tags: ["대형좌대", "숙박가능", "취사", "참돔", "가족"],
    transportInfo: "법환포구에서 선박 10분 (오전 5시·6시 출발)",
    bestSeason: ["봄", "가을"], catchRate: "상", hasAccommodation: true,
    schedule: "주간 04:00 픽업 출발 / 18:00 귀환 | 야간 17:00 출발 / 익일 07:00 귀환",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "jw2", name: "모슬포 방어좌대", region: "모슬포",
    location: "대정읍 모슬포항 앞바다 2km", operatorName: "대정수산", operatorPhone: "064-794-0002",
    description: "겨울 방어 시즌 최고의 좌대. 12~2월 방어·부시리 조황 압도적. 선상낚시와 병행 가능. 방어 지깅 전문 가이드 상주.",
    targetFish: ["방어", "부시리", "삼치", "참돔"],
    facilities: ["낚시대 대여", "생미끼·루어 대여", "화장실", "간식 제공"],
    priceDay: 65000, capacity: 20, availableSeats: 5,
    rating: 4.9, reviewCount: 89, tags: ["방어", "겨울시즌", "루어", "지깅전문"],
    transportInfo: "모슬포항에서 선박 15분 (오전 6시 출발)",
    bestSeason: ["겨울"], catchRate: "상", hasAccommodation: false,
    schedule: "06:00 출발 / 16:00 귀환",
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "jw3", name: "한림 비양도 좌대", region: "한림",
    location: "한림읍 비양도 서쪽 해역 0.8km", operatorName: "비양도수산", operatorPhone: "064-796-0003",
    description: "비양도 주변 청정 해역 좌대. 참돔·벵에돔·볼락 풍부. 비양도 경관 보며 낚시하는 특별한 경험. 20인 수용.",
    targetFish: ["참돔", "벵에돔", "볼락", "감성돔"],
    facilities: ["낚시대 대여", "생미끼 제공", "화장실", "취사 가능"],
    priceDay: 50000, capacity: 20, availableSeats: 12,
    rating: 4.7, reviewCount: 76, tags: ["비양도경관", "취사", "참돔", "벵에돔"],
    transportInfo: "한림항에서 선박 20분 (오전 5시·6시 출발)",
    bestSeason: ["봄", "여름", "가을"], catchRate: "상", hasAccommodation: false,
    schedule: "05:00 출발 / 17:00 귀환",
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "jw4", name: "성산 일출 좌대", region: "성산",
    location: "성산읍 오조리 앞바다 1.5km", operatorName: "성산수산", operatorPhone: "064-784-0004",
    description: "성산 일출봉이 보이는 환상적인 뷰의 좌대. 일출 감상과 낚시를 동시에! 반열기·참돔·부시리 조황 우수.",
    targetFish: ["반열기", "참돔", "부시리", "방어"],
    facilities: ["낚시대 대여", "생미끼 제공", "화장실", "커피·라면 제공"],
    priceDay: 60000, capacity: 15, availableSeats: 3,
    rating: 4.6, reviewCount: 54, tags: ["일출뷰", "반열기", "참돔", "성산"],
    transportInfo: "성산포항에서 선박 15분 (오전 4시 30분 출발)",
    bestSeason: ["봄", "여름", "가을"], catchRate: "상", hasAccommodation: false,
    schedule: "04:30 출발 / 15:00 귀환",
    createdAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "jw5", name: "서귀포 범섬 좌대", region: "서귀포",
    location: "서귀포시 범섬 동쪽 해역", operatorName: "범섬수산", operatorPhone: "064-733-0005",
    description: "범섬 주변 참돔 성지 좌대. 50cm급 대형 참돔 출현 빈도 높음. 프로 낚시꾼들이 선호하는 최고급 포인트.",
    targetFish: ["참돔", "반열기", "감성돔", "돌돔"],
    facilities: ["낚시대 대여", "고급 생미끼 제공", "화장실", "샤워시설"],
    priceDay: 75000, priceNight: 100000, capacity: 12, availableSeats: 2,
    rating: 5.0, reviewCount: 38, tags: ["프리미엄", "참돔", "대형어", "범섬"],
    transportInfo: "서귀포항에서 선박 20분 (오전 4시 출발)",
    bestSeason: ["봄", "가을"], catchRate: "상", hasAccommodation: false,
    schedule: "04:00 출발 / 16:00 귀환",
    createdAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "jw6", name: "애월 유리바다 좌대", region: "애월",
    location: "애월읍 고내리 앞바다 1km", operatorName: "애월수산", operatorPhone: "064-799-0006",
    description: "애월 앞바다 유리처럼 투명한 바다에서의 좌대낚시. 가족 단위 추천. 어린이 낚시 지도 서비스.",
    targetFish: ["볼락", "전갱이", "감성돔", "넙치"],
    facilities: ["낚시대 대여(어린이용 포함)", "생미끼 제공", "화장실", "취사 가능", "구명조끼"],
    priceDay: 45000, capacity: 25, availableSeats: 15,
    rating: 4.5, reviewCount: 112, tags: ["가족낚시", "어린이환영", "취사", "애월"],
    transportInfo: "고내포구에서 선박 10분 (오전 6시·7시 출발)",
    bestSeason: ["봄", "여름", "가을"], catchRate: "중", hasAccommodation: false,
    schedule: "06:00 출발 / 17:00 귀환",
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "jw7", name: "구좌 우도 앞 좌대", region: "구좌",
    location: "구좌읍 종달리 앞바다 우도 인근", operatorName: "구좌수산", operatorPhone: "064-782-0007",
    description: "우도가 보이는 구좌 앞바다 좌대. 반열기·참돔 다수 서식. 우도 관광 전후로 낚시하기 최적.",
    targetFish: ["반열기", "참돔", "벵에돔"],
    facilities: ["낚시대 대여", "생미끼 제공", "화장실"],
    priceDay: 55000, capacity: 18, availableSeats: 7,
    rating: 4.4, reviewCount: 48, tags: ["우도뷰", "반열기", "참돔"],
    transportInfo: "종달리 선착장에서 선박 15분 (오전 5시 30분 출발)",
    bestSeason: ["봄", "여름", "가을"], catchRate: "중", hasAccommodation: false,
    schedule: "05:30 출발 / 16:00 귀환",
    createdAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "jw8", name: "서귀포 문섬 프리미엄 좌대", region: "서귀포",
    location: "서귀포시 문섬 인근 해역", operatorName: "문섬수산", operatorPhone: "064-733-0008",
    description: "문섬 갯바위와 연계되는 프리미엄 좌대. 벵에돔 명포인트. 다이버들도 즐겨 찾는 청정 수중 환경.",
    targetFish: ["벵에돔", "감성돔", "참돔", "돌돔"],
    facilities: ["낚시대 대여", "고급 생미끼 제공", "화장실", "샤워시설", "WiFi"],
    priceDay: 80000, capacity: 10, availableSeats: 0,
    rating: 4.9, reviewCount: 67, tags: ["프리미엄", "벵에돔", "문섬", "청정해역"],
    transportInfo: "서귀포항에서 선박 15분 (오전 5시 출발)",
    bestSeason: ["봄", "가을"], catchRate: "상", hasAccommodation: false,
    schedule: "05:00 출발 / 17:00 귀환 (만석, 예약 필요)",
    createdAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "jw9", name: "한림 협재 가족 좌대", region: "한림",
    location: "한림읍 협재 앞바다 0.7km", operatorName: "협재수산", operatorPhone: "064-796-0009",
    description: "협재 해수욕장 뷰를 즐기며 낚시. 가족 단위, 연인 커플 추천. 투명 카약 함께 대여 가능.",
    targetFish: ["볼락", "전갱이", "넙치"],
    facilities: ["낚시대 대여", "생미끼 제공", "화장실", "취사 가능", "카약 대여"],
    priceDay: 40000, capacity: 20, availableSeats: 10,
    rating: 4.3, reviewCount: 89, tags: ["가족", "커플", "협재뷰", "카약"],
    transportInfo: "협재해수욕장 선착장에서 선박 5분 (매시간 출발)",
    bestSeason: ["봄", "여름"], catchRate: "중", hasAccommodation: false,
    schedule: "07:00~18:00 (매시간 출발)",
    createdAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "jw10", name: "성산 선상·좌대 복합", region: "성산",
    location: "성산읍 신산리 앞바다 2km", operatorName: "신산수산", operatorPhone: "064-784-0010",
    description: "좌대낚시 + 선상낚시 복합 패키지. 오전 좌대, 오후 선상낚시로 이동. 방어·부시리·참돔 모두 겨냥.",
    targetFish: ["방어", "부시리", "참돔", "삼치"],
    facilities: ["낚시대 대여", "루어·생미끼 모두 제공", "화장실", "취사 가능"],
    priceDay: 85000, capacity: 16, availableSeats: 4,
    rating: 4.8, reviewCount: 41, tags: ["복합패키지", "방어", "선상+좌대"],
    transportInfo: "성산포항에서 선박 20분 (오전 5시 출발)",
    bestSeason: ["봄", "가을", "겨울"], catchRate: "상", hasAccommodation: false,
    schedule: "05:00 좌대 → 오후 선상이동 → 17:00 귀환",
    createdAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "jw11", name: "모슬포 참치·방어 원정 좌대", region: "모슬포",
    location: "대정읍 앞바다 5km 원거리", operatorName: "대정원정수산", operatorPhone: "064-794-0011",
    description: "소형 참치(바다조각) 출현하는 원거리 좌대. 방어·부시리 대형급 기대 가능. 체력 강한 고수 전용.",
    targetFish: ["소형참치", "방어", "부시리", "삼치"],
    facilities: ["루어 대여", "화장실", "간식·음료"],
    priceDay: 100000, capacity: 10, availableSeats: 2,
    rating: 4.7, reviewCount: 22, tags: ["원거리", "참치", "방어", "고수전용"],
    transportInfo: "모슬포항에서 선박 40분 (오전 5시 출발)",
    bestSeason: ["여름", "가을"], catchRate: "상", hasAccommodation: false,
    schedule: "05:00 출발 / 17:00 귀환",
    createdAt: "2026-04-05T00:00:00Z",
  },
  {
    id: "jw12", name: "제주시 이호 근해 좌대", region: "제주시",
    location: "제주시 이호테우해변 앞바다 0.5km", operatorName: "이호수산", operatorPhone: "064-720-0012",
    description: "제주공항 근처 접근성 최고 좌대. 비행기 타기 전·후로 낚시 가능. 간단한 낚시 체험 1~2시간 코스도 운영.",
    targetFish: ["전갱이", "볼락", "넙치"],
    facilities: ["낚시대 대여", "생미끼 제공", "화장실"],
    priceDay: 35000, capacity: 30, availableSeats: 20,
    rating: 4.1, reviewCount: 203, tags: ["접근성최고", "공항근처", "체험낚시", "초보"],
    transportInfo: "이호테우해변에서 선박 5분 (매시간 출발)",
    bestSeason: ["봄", "여름", "가을"], catchRate: "중", hasAccommodation: false,
    schedule: "07:00~19:00 (매시간 출발)",
    createdAt: "2026-04-10T00:00:00Z",
  },
  {
    id: "jw13", name: "서귀포 야간 갈치 좌대", region: "서귀포",
    location: "서귀포시 강정 앞바다 1.5km", operatorName: "강정수산", operatorPhone: "064-732-0013",
    description: "야간 전용 갈치 좌대. 집어등으로 갈치 유인. F3~F4지 대형 갈치 다수 출현. 야간 낚시 특별 체험.",
    targetFish: ["갈치", "전갱이"],
    facilities: ["전동릴 대여", "갈치 루어 포함", "화장실", "야간 집어등", "간식 제공"],
    priceDay: 60000, capacity: 20, availableSeats: 6,
    rating: 4.6, reviewCount: 61, tags: ["야간전용", "갈치", "집어등", "전동릴"],
    transportInfo: "강정포구에서 선박 10분 (오후 6시 출발)",
    bestSeason: ["여름", "가을", "겨울"], catchRate: "상", hasAccommodation: false,
    schedule: "18:00 출발 / 01:00 귀환",
    createdAt: "2026-04-15T00:00:00Z",
  },
  {
    id: "jw14", name: "애월 숙박형 프리미엄 좌대", region: "애월",
    location: "애월읍 앞바다 2km", operatorName: "애월프리미엄수산", operatorPhone: "064-799-0014",
    description: "애월 앞바다 숙박형 2일 1박 좌대 패키지. 저녁 갈치 + 새벽 감성돔. 요리 서비스 포함.",
    targetFish: ["갈치", "감성돔", "볼락"],
    facilities: ["낚시대 대여", "생미끼 포함", "화장실", "숙박시설", "요리서비스", "WiFi", "샤워"],
    priceDay: 120000, priceNight: 120000, capacity: 12, availableSeats: 4,
    rating: 4.9, reviewCount: 29, tags: ["숙박형", "2일1박", "갈치+감성돔", "요리서비스"],
    transportInfo: "고내포구에서 선박 15분 (오후 4시 출발)",
    bestSeason: ["봄", "가을"], catchRate: "상", hasAccommodation: true,
    schedule: "1일차 16:00 출발 → 야간 갈치 → 숙박 → 새벽 감성돔 → 2일차 10:00 귀환",
    createdAt: "2026-04-20T00:00:00Z",
  },
  {
    id: "jw15", name: "성산 초보 체험 좌대", region: "성산",
    location: "성산읍 성산포구 앞바다 0.5km", operatorName: "성산체험수산", operatorPhone: "064-784-0015",
    description: "낚시 처음이어도 OK! 전문 강사 1:1 가이드. 아이부터 어르신까지. 잡은 물고기 즉석 회 서비스.",
    targetFish: ["전갱이", "볼락", "넙치"],
    facilities: ["낚시대 제공", "미끼 포함", "화장실", "구명조끼", "1:1가이드", "즉석회 서비스"],
    priceDay: 30000, capacity: 30, availableSeats: 18,
    rating: 4.4, reviewCount: 315, tags: ["초보전용", "1:1가이드", "즉석회", "가족", "어린이"],
    transportInfo: "성산포구에서 선박 5분 (오전 9시·오후 1시 출발)",
    bestSeason: ["봄", "여름", "가을"], catchRate: "중", hasAccommodation: false,
    schedule: "09:00 또는 13:00 출발 / 3시간 코스",
    createdAt: "2026-05-01T00:00:00Z",
  },
];
