import { Post } from "./types";

export const DUMMY_POSTS: Post[] = [
  {
    id: "pt1", category: "조황", title: "[법환방파제] 5/10 감성돔 42cm 2마리 조황입니다",
    content: "오전 7시부터 10시까지 3시간. 7물 조류. 원줄 3호 목줄 2호 G2찌 세팅. 크릴 반마리에 감성돔 연속 히트. 법환 북방파제 끝 테트라포드 틈에서 나왔어요.",
    authorName: "서귀포갯바위왕", authorLevel: "고수", region: "서귀포",
    tags: ["감성돔", "법환", "찌낚시"], likeCount: 47, commentCount: 12, viewCount: 380,
    createdAt: "2026-05-10T11:00:00Z",
  },
  {
    id: "pt2", category: "질문", title: "제주 초보인데 갯바위낚시 처음 가려고 합니다. 장비 추천 부탁해요",
    content: "제주 여행 중인데 반나절 갯바위 낚시 가보고 싶어요. 낚시 경험 전혀 없는 초보인데 어디서 뭘 준비해야 하나요? 렌탈샵 있나요?",
    authorName: "서울에서온낚린이", authorLevel: "초보",
    tags: ["초보", "장비추천", "갯바위", "렌탈"], likeCount: 8, commentCount: 15, viewCount: 243,
    createdAt: "2026-05-09T18:00:00Z",
  },
  {
    id: "pt3", category: "장터", title: "[판매] 시마노 BB-X 데스피나 1500D — 50만원 (성산 직거래 가능)",
    content: "작년에 구입 후 5회 사용. 스풀 교환 포함 풀세트. 성산 직거래 원합니다. 박스·보증서 있음. 흠집 없는 A급.",
    authorName: "장비업그레이드중", authorLevel: "중급",
    tags: ["릴", "시마노", "장터", "성산"], likeCount: 3, commentCount: 7, viewCount: 156,
    createdAt: "2026-05-08T14:00:00Z",
  },
  {
    id: "pt4", category: "자유", title: "처음으로 방어 잡았을 때 그 기억 아직도... ㅋㅋ",
    content: "4년 전 제주 여행 와서 우연히 낚시 체험했다가 방어 65cm가 걸려버렸고... 그게 낚시에 빠진 계기가 됐어요. 지금은 1년에 4번 제주 낚시 원정 다닙니다 ㅎㅎ",
    authorName: "방어한방에빠진남자", authorLevel: "중급",
    tags: ["자유", "방어", "낚시입문기"], likeCount: 34, commentCount: 22, viewCount: 412,
    createdAt: "2026-05-07T20:00:00Z",
  },
  {
    id: "pt5", category: "후기", title: "황금좌대 후기 — 참돔 51cm 잡았어요!",
    content: "황금좌대 처음 가봤는데 직원분이 진짜 친절하게 도와주셨어요. 수심 세팅부터 미끼 달기까지. 참돔 51cm는 생애 첫 대형 참돔! 다음에 또 갈 예정.",
    authorName: "좌대매니아", authorLevel: "중급",
    tags: ["황금좌대", "참돔", "후기", "서귀포"], likeCount: 63, commentCount: 17, viewCount: 589,
    createdAt: "2026-05-06T16:00:00Z",
  },
  {
    id: "pt6", category: "질문", title: "물때표 보는 방법 알려주세요",
    content: "낚시 갈 때 물때가 중요하다는 건 알겠는데 1물~15물이 뭔지, 어떤 물때가 좋은지 모르겠어요. 쉽게 설명해주실 수 있는 분 계신가요?",
    authorName: "물때뭐야", authorLevel: "초보",
    tags: ["물때", "초보질문", "조류"], likeCount: 15, commentCount: 28, viewCount: 445,
    createdAt: "2026-05-05T10:00:00Z",
  },
  {
    id: "pt7", category: "조황", title: "[성산 선상] 부시리 90cm 나왔습니다 대박",
    content: "성산 앞바다 지깅. 메탈지그 200g으로 바닥층 탐색 중 대물 히트. 30분 파이팅 끝에 올린 부시리 90cm. 올해 최고 기록입니다.",
    authorName: "선상고수박", authorLevel: "프로", region: "성산",
    tags: ["부시리", "90cm", "선상", "지깅", "성산"], likeCount: 142, commentCount: 38, viewCount: 1203,
    isPinned: false,
    createdAt: "2026-05-04T18:00:00Z",
  },
  {
    id: "pt8", category: "장터", title: "[구매] 시마노 원정급 지깅대 구합니다 — 예산 30만원",
    content: "선상 지깅용 6피트 120g 부하 로드 구합니다. 시마노 또는 다이와. 제주 직거래 가능하신 분 연락주세요.",
    authorName: "루어마스터최", authorLevel: "프로",
    tags: ["지깅대", "구매", "시마노", "다이와"], likeCount: 2, commentCount: 5, viewCount: 88,
    createdAt: "2026-05-03T13:00:00Z",
  },
  {
    id: "pt9", category: "자유", title: "갯바위 가면 항상 느끼는 것... 자연 앞에서 작아지는 느낌",
    content: "어젯밤 11시에 혼자 갯바위 앉아서 낚시하다가 별 보면서 든 생각. 낚시가 그냥 물고기 잡는 게 아니구나 싶더라고요. 이래서 낚시 못 끊는 것 같아요.",
    authorName: "갯바위철학자", authorLevel: "고수",
    tags: ["자유", "감성", "갯바위"], likeCount: 89, commentCount: 31, viewCount: 673,
    createdAt: "2026-05-02T08:00:00Z",
  },
  {
    id: "pt10", category: "후기", title: "모슬포 야간 갈치 선상 후기 — F4지 20마리!",
    content: "제 낚시 인생 최고의 하루였어요. F4지 갈치 20마리. 선장님 포인트 잘 잡아주시고 집어등도 빵빵하게. 전동릴 처음 써봤는데 편하더라고요. 강추!",
    authorName: "모슬포갈치선장", authorLevel: "프로",
    tags: ["갈치", "모슬포", "선상", "야간", "후기"], likeCount: 99, commentCount: 31, viewCount: 847,
    createdAt: "2026-05-01T09:00:00Z",
  },
  {
    id: "pt11", category: "질문", title: "제주 갯바위 처음인데 조석예보 어디서 보나요?",
    content: "갯바위 낚시 가려는데 파도 높이랑 물때 확인하는 사이트 추천해주세요. 기상청 말고 낚시 전용으로 보기 좋은 곳 있나요?",
    authorName: "갯바위입문자", authorLevel: "초보",
    tags: ["갯바위", "조석예보", "초보질문", "파도"], likeCount: 12, commentCount: 19, viewCount: 312,
    createdAt: "2026-04-30T14:00:00Z",
  },
  {
    id: "pt12", category: "조황", title: "[범섬 선상] 참돔 65cm 대물 — 서귀포 범섬 성지 인증",
    content: "범섬 선상에서 참돔 65cm 드디어 잡았습니다! 코 찌르는 냄새 나는 살아있는 새우 미끼 최강이에요. 바닥층 4m 수심 공략. 파이팅 20분.",
    authorName: "서귀포참돔박사", authorLevel: "프로", region: "서귀포",
    tags: ["참돔", "65cm", "범섬", "서귀포", "대물"], likeCount: 154, commentCount: 45, viewCount: 1456,
    createdAt: "2026-04-29T18:00:00Z",
  },
  {
    id: "pt13", category: "자유", title: "낚시하다 바다거북 만난 썰 ㅋㅋㅋ",
    content: "어제 한림 갯바위에서 낚시하는데 바다거북이 유유히 지나감... 제주바다 진짜 청정하구나 느꼈어요. 낚시는 한 마리도 못 잡고 거북이만 봤지만 만족ㅋ",
    authorName: "자연주의낚시꾼", authorLevel: "중급",
    tags: ["자유", "바다거북", "한림", "제주바다"], likeCount: 67, commentCount: 24, viewCount: 523,
    createdAt: "2026-04-28T21:00:00Z",
  },
  {
    id: "pt14", category: "후기", title: "성산 초보 체험 좌대 가족 후기 — 아이도 넙치 잡았어요",
    content: "초등학생 아들이랑 처음 낚시 체험 갔는데 대만족. 직원분이 처음부터 끝까지 도와주셨고 아이가 넙치 잡고 너무 좋아했어요. 즉석 회도 맛있었고 강력 추천!",
    authorName: "제주여행가족", authorLevel: "초보",
    tags: ["좌대", "가족후기", "초보체험", "성산"], likeCount: 45, commentCount: 13, viewCount: 398,
    createdAt: "2026-04-27T16:00:00Z",
  },
  {
    id: "pt15", category: "장터", title: "[판매] 다이와 크로스비트 EX 3.35m — 25만원",
    content: "갯바위 찌낚시용 3.35m 로드. 2년 사용. 가이드 교체 완료. 서귀포 직거래 or 택배 가능(착불). 사진 DM 주세요.",
    authorName: "장비정리중", authorLevel: "고수",
    tags: ["낚싯대", "판매", "다이와", "갯바위"], likeCount: 4, commentCount: 8, viewCount: 134,
    createdAt: "2026-04-26T12:00:00Z",
  },
  {
    id: "pt16", category: "자유", title: "낚시 10년차 되니까 드는 생각 — 초보분들 보세요",
    content: "낚시 10년 하면서 느낀 것: 1) 장비보다 포인트 공부가 먼저 2) 물때 공부는 필수 3) 고수 옆에서 배우는 게 유튜브보다 100배 빠름. 초보 때 이거 알았으면 시행착오 줄었을 텐데.",
    authorName: "10년차낚시인", authorLevel: "프로",
    tags: ["자유", "낚시팁", "10년차", "초보에게"], likeCount: 123, commentCount: 47, viewCount: 1087,
    createdAt: "2026-04-25T10:00:00Z",
  },
  {
    id: "pt17", category: "조황", title: "[한림 야간 선상] 갈치 F3지 15마리 대박",
    content: "한림 갈치 선상 야간. F3지 갈치 15마리. 전동릴에 갈치커터 달고 집어등 아래에서 작업. 새벽 1시까지 입질 계속. 올해 첫 갈치 원정 대성공.",
    authorName: "한림선상왕", authorLevel: "고수", region: "한림",
    tags: ["갈치", "한림", "선상", "야간", "F3지"], likeCount: 61, commentCount: 22, viewCount: 489,
    createdAt: "2026-04-24T22:00:00Z",
  },
  {
    id: "pt18", category: "질문", title: "찌낚시 찌 고르는 방법 알려주세요",
    content: "낚시 2개월차인데 찌가 너무 종류가 많아서 뭘 사야 할지 모르겠어요. 방파제 감성돔 찌낚시 기준으로 어떤 찌 사면 좋을까요?",
    authorName: "찌뭐사야해", authorLevel: "초보",
    tags: ["찌", "초보질문", "찌낚시", "감성돔"], likeCount: 18, commentCount: 32, viewCount: 367,
    createdAt: "2026-04-23T15:00:00Z",
  },
  {
    id: "pt19", category: "후기", title: "문섬 도선 갯바위 후기 — 도선비 35,000원 가성비 최고",
    content: "문섬 도선 타고 갯바위 진짜 대박. 벵에돔 5마리+감성돔 1마리. 도선비 35,000원이 좀 세다 싶었는데 입장료 같은 개념이라 생각하면 완전 가성비. 다음에 또 갈 예정.",
    authorName: "서귀포대물꾼", authorLevel: "프로",
    tags: ["문섬", "도선", "갯바위", "벵에돔", "후기"], likeCount: 95, commentCount: 28, viewCount: 734,
    createdAt: "2026-04-22T11:00:00Z",
  },
  {
    id: "pt20", category: "자유", title: "올해 제주 낚시 원정 계획 세우는 중 — 같이 갈 사람?",
    content: "올해 봄·가을 각 한 번씩 제주 낚시 원정 계획 중. 4박5일로 서귀포+성산+한림 전역 포인트 탐방 예정. 관심 있는 분 댓글로.",
    authorName: "원정계획중", authorLevel: "중급",
    tags: ["원정계획", "자유", "제주여행", "동행구함"], likeCount: 28, commentCount: 19, viewCount: 312,
    createdAt: "2026-04-21T14:00:00Z",
  },
  {
    id: "pt21", category: "조황", title: "[구좌 세화리] 돌돔 38cm + 감성돔 44cm 조황",
    content: "세화리 갯바위 명포인트. 돌돔 38cm 구좌에서 처음! 성게 미끼로 바닥층 공략. 감성돔도 추가. 9물 조류 딱 맞았을 때 입질 폭발.",
    authorName: "구좌낚시러버", authorLevel: "고수", region: "구좌",
    tags: ["돌돔", "감성돔", "구좌", "세화리", "성게미끼"], likeCount: 55, commentCount: 14, viewCount: 478,
    createdAt: "2026-04-20T12:00:00Z",
  },
  {
    id: "pt22", category: "자유", title: "낚시 갔다가 폭풍우 맞은 썰 (공포체험)",
    content: "갯바위에 있다가 갑자기 먹구름... 스마트폰 날씨 앱은 맑음이었는데 해상 기상이 내륙이랑 다르다는 걸 그날 뼈저리게 배웠습니다. 해경 도움으로 겨우 귀환. 낚시 전 해상 기상 꼭 확인하세요.",
    authorName: "폭풍우생존자", authorLevel: "중급",
    tags: ["자유", "안전", "해상기상", "경험담"], likeCount: 187, commentCount: 64, viewCount: 2341,
    createdAt: "2026-04-19T09:00:00Z",
  },
  {
    id: "pt23", category: "후기", title: "비양도 좌대 1박2일 커플 후기",
    content: "남자친구랑 비양도 좌대 1박 다녀왔어요. 비양도 경관 보면서 낚시하는 게 진짜 낭만 그 자체. 참돔 45cm 잡고 둘이 회 떠먹었는데 감동이었어요. 커플 여행으로 강추!",
    authorName: "낚시하는커플", authorLevel: "초보",
    tags: ["비양도", "좌대", "커플", "1박", "후기"], likeCount: 72, commentCount: 19, viewCount: 623,
    createdAt: "2026-04-18T15:00:00Z",
  },
  {
    id: "pt24", category: "장터", title: "[판매] 크릴 30박스 (미개봉) — 제주시 직거래 4만원",
    content: "원정 취소로 인해 냉동 크릴 30박스 처분합니다. 3L사이즈. 미개봉 신선 상태. 제주시 자택 직거래만 가능.",
    authorName: "원정취소된", authorLevel: "고수",
    tags: ["크릴", "판매", "미끼", "제주시"], likeCount: 6, commentCount: 11, viewCount: 178,
    createdAt: "2026-04-17T10:00:00Z",
  },
  {
    id: "pt25", category: "조황", title: "[이호테우 방파제] 넙치 55cm 야간 원투 대박",
    content: "야간 원투로 55cm 넙치 처음 경험! 갯지렁이+크릴 합사 미끼로 원투. 이호테우 방파제 내항쪽 모래바닥 포인트. 넙치는 바닥에 있으니 무거운 봉돌 써야.",
    authorName: "제주시야간꾼", authorLevel: "중급", region: "제주시",
    tags: ["넙치", "이호테우", "야간", "원투", "55cm"], likeCount: 48, commentCount: 13, viewCount: 421,
    createdAt: "2026-04-16T23:00:00Z",
  },
  {
    id: "pt26", category: "질문", title: "좌대낚시 처음인데 미끼는 뭘 써야 하나요?",
    content: "다음 달 황금좌대 예약했어요. 좌대에서 어떤 미끼가 효과적인지, 어떤 채비를 써야 하는지 알려주세요. 좌대 직원이 다 알려준다고는 하는데 미리 공부하고 싶어요.",
    authorName: "좌대처음이야", authorLevel: "초보",
    tags: ["좌대", "미끼", "채비", "초보질문"], likeCount: 11, commentCount: 24, viewCount: 298,
    createdAt: "2026-04-15T12:00:00Z",
  },
];
