import { FishingGathering } from "./types";

export const DUMMY_GATHERINGS: FishingGathering[] = [
  {
    id: "g1", title: "법환 방파제 감성돔 찌낚시 동행 (초보 환영)",
    hostName: "서귀포갯바위왕", hostRating: 4.9, hostCatchCount: 234,
    region: "서귀포", location: "법환포구 북방파제", spotType: "방파제", fishingMethod: "찌낚시",
    targetFish: ["감성돔", "벵에돔"], date: "2026-05-17", time: "05:30",
    maxMembers: 4, currentMembers: 2,
    costType: "split", costAmount: 20000, costNote: "크릴 1박스 공동 구매 + 교통비",
    equipmentProvided: true, beginnerWelcome: true,
    description: "여분 낚싯대 2대 있어요. 찌맞춤부터 알려드립니다. 오전에 잡고 근처 횟집에서 소주 한 잔까지!",
    tags: ["초보환영", "장비제공", "감성돔", "법환", "찌낚시"],
    createdAt: "2026-05-11T09:00:00Z",
  },
  {
    id: "g2", title: "성산 선상 루어 — 방어·부시리 노려봅니다",
    hostName: "루어마스터최", hostRating: 4.8, hostCatchCount: 512,
    region: "성산", location: "성산포항 출발 선상", spotType: "선상", fishingMethod: "루어",
    targetFish: ["방어", "부시리", "삼치"], date: "2026-05-18", time: "05:00",
    maxMembers: 6, currentMembers: 4,
    costType: "split", costAmount: 80000, costNote: "선박 대여비 1/n (5~6인 기준)",
    equipmentProvided: false, beginnerWelcome: false,
    description: "루어낚시 경험자 우대. 최소 메탈지그 60g~150g 세팅 필요. 쿨러 지참 필수.",
    tags: ["방어", "부시리", "루어", "선상", "성산", "중급이상"],
    createdAt: "2026-05-10T15:00:00Z",
  },
  {
    id: "g3", title: "한림 야간 볼락 루어 — 오후 8시 출발",
    hostName: "한림볼락헌터", hostRating: 4.7, hostCatchCount: 389,
    region: "한림", location: "한림항 방파제", spotType: "방파제", fishingMethod: "루어",
    targetFish: ["볼락", "전갱이"], date: "2026-05-17", time: "20:00",
    maxMembers: 5, currentMembers: 3,
    costType: "split", costAmount: 10000, costNote: "웜 공동 구매비",
    equipmentProvided: false, beginnerWelcome: true,
    description: "야간 볼락 루어 함께 해요. 2g 지그헤드 + 1.5인치 웜 세팅. 라이트 루어대 있으면 가져오세요.",
    tags: ["볼락", "야간", "루어", "한림", "초보환영"],
    createdAt: "2026-05-09T18:00:00Z",
  },
  {
    id: "g4", title: "모슬포 방어좌대 동행 (주중 평일)",
    hostName: "모슬포방어헌터", hostRating: 4.6, hostCatchCount: 178,
    region: "모슬포", location: "모슬포 방어좌대", spotType: "좌대", fishingMethod: "좌대낚시",
    targetFish: ["방어", "참돔"], date: "2026-05-20", time: "06:00",
    maxMembers: 4, currentMembers: 1,
    costType: "fixed", costAmount: 65000, costNote: "좌대 1인 요금 (미끼 포함)",
    equipmentProvided: true, beginnerWelcome: true,
    description: "평일이라 자리 여유 있어요. 처음 좌대 가시는 분도 환영. 방어 지깅 노하우 알려드릴게요.",
    tags: ["방어", "좌대", "모슬포", "평일", "초보환영"],
    createdAt: "2026-05-08T10:00:00Z",
  },
  {
    id: "g5", title: "구좌 세화리 갯바위 찌낚시 동행",
    hostName: "구좌낚시러버", hostRating: 4.8, hostCatchCount: 297,
    region: "구좌", location: "구좌 세화리 갯바위", spotType: "갯바위", fishingMethod: "찌낚시",
    targetFish: ["돌돔", "감성돔", "벵에돔"], date: "2026-05-22", time: "06:00",
    maxMembers: 3, currentMembers: 1,
    costType: "split", costAmount: 30000, costNote: "크릴+밑밥 공동 구매 + 교통비",
    equipmentProvided: false, beginnerWelcome: false,
    description: "세화리 갯바위 명포인트. 돌돔 노려봅니다. 원줄 4호 이상 세팅 필수. 중급 이상 환영.",
    tags: ["돌돔", "감성돔", "갯바위", "구좌", "중급이상"],
    createdAt: "2026-05-07T14:00:00Z",
  },
  {
    id: "g6", title: "제주 낚시 왕초보 모임 — 방파제 체험 낚시",
    hostName: "초보케어전문가", hostRating: 4.9, hostCatchCount: 156,
    region: "제주시", location: "이호테우해변 방파제", spotType: "방파제", fishingMethod: "생미끼",
    targetFish: ["전갱이", "볼락"], date: "2026-05-24", time: "09:00",
    maxMembers: 6, currentMembers: 4,
    costType: "split", costAmount: 15000, costNote: "낚싯대 대여비 + 미끼비",
    equipmentProvided: true, beginnerWelcome: true,
    description: "낚시 처음이신 분들 모집! 장비부터 채비법, 미끼 달기까지 처음부터 알려드려요. 어린이 참여 가능.",
    tags: ["왕초보", "장비제공", "가족", "이호테우", "제주시"],
    createdAt: "2026-05-06T11:00:00Z",
  },
  {
    id: "g7", title: "서귀포 문섬 갯바위 벵에돔 원정 (4인)",
    hostName: "서귀포대물꾼", hostRating: 4.7, hostCatchCount: 423,
    region: "서귀포", location: "문섬 갯바위 (도선 이용)", spotType: "갯바위", fishingMethod: "찌낚시",
    targetFish: ["벵에돔", "감성돔"], date: "2026-05-25", time: "04:30",
    maxMembers: 4, currentMembers: 3,
    costType: "split", costAmount: 50000, costNote: "도선비 35,000 + 크릴·밑밥",
    equipmentProvided: false, beginnerWelcome: false,
    description: "문섬 도선 이용 갯바위 벵에돔 원정. 마지막 자리 1명 모집. 원줄 2.5호 이상 세팅 필수.",
    tags: ["벵에돔", "문섬", "갯바위", "도선", "서귀포", "고수"],
    createdAt: "2026-05-05T16:00:00Z",
  },
  {
    id: "g8", title: "애월 수산리 갯바위 루어 (농어·부시리 타겟)",
    hostName: "애월루어꾼", hostRating: 4.5, hostCatchCount: 201,
    region: "애월", location: "애월 수산리 갯바위", spotType: "갯바위", fishingMethod: "루어",
    targetFish: ["농어", "부시리"], date: "2026-05-16", time: "16:00",
    maxMembers: 4, currentMembers: 2,
    costType: "free", costNote: "각자 미끼·루어 준비",
    equipmentProvided: false, beginnerWelcome: false,
    description: "석양 무렵 농어 입질 집중 포인트. 미노우 루어 필수. 루어 중급자 이상.",
    tags: ["농어", "부시리", "루어", "석양", "애월", "갯바위"],
    createdAt: "2026-05-04T13:00:00Z",
  },
  {
    id: "g9", title: "성산 일출 선상낚시 (5인 미니선 대절)",
    hostName: "선상고수박", hostRating: 4.9, hostCatchCount: 634,
    region: "성산", location: "성산포항 출발", spotType: "선상", fishingMethod: "선상",
    targetFish: ["참돔", "방어", "삼치"], date: "2026-05-19", time: "04:30",
    maxMembers: 5, currentMembers: 3,
    costType: "split", costAmount: 70000, costNote: "미니선 대절 5인 1/n",
    equipmentProvided: false, beginnerWelcome: false,
    description: "성산 일출 선상. 새벽 일출 감상하며 참돔 지깅. 미니선 대절로 여유롭게. 선상 경험자 우대.",
    tags: ["참돔", "선상", "일출", "성산", "대절"],
    createdAt: "2026-05-03T10:00:00Z",
  },
  {
    id: "g10", title: "한림 협재 방파제 가족 낚시 모임",
    hostName: "협재낚시가족", hostRating: 4.6, hostCatchCount: 88,
    region: "한림", location: "협재 방파제", spotType: "방파제", fishingMethod: "생미끼",
    targetFish: ["볼락", "전갱이"], date: "2026-05-23", time: "10:00",
    maxMembers: 10, currentMembers: 6,
    costType: "split", costAmount: 10000, costNote: "미끼비 1/n",
    equipmentProvided: true, beginnerWelcome: true,
    description: "아이들과 함께하는 가족 낚시 모임. 장비 여분 있어요. 잡은 물고기 회 떠드릴 수 있어요 ^^",
    tags: ["가족낚시", "어린이환영", "협재", "한림", "초보환영"],
    createdAt: "2026-05-02T09:00:00Z",
  },
  {
    id: "g11", title: "모슬포 야간 갈치 선상 (야간 전문)",
    hostName: "모슬포갈치선장", hostRating: 4.8, hostCatchCount: 445,
    region: "모슬포", location: "모슬포항 야간 선상", spotType: "선상", fishingMethod: "선상",
    targetFish: ["갈치"], date: "2026-05-21", time: "18:00",
    maxMembers: 8, currentMembers: 5,
    costType: "fixed", costAmount: 55000, costNote: "선상 1인 요금 (전동릴·루어 포함)",
    equipmentProvided: true, beginnerWelcome: true,
    description: "야간 갈치 선상 전문. 전동릴 달아드리니까 처음도 OK. 귀환 후 갈치 회 같이 먹을 수 있어요.",
    tags: ["갈치", "야간", "선상", "모슬포", "장비제공"],
    createdAt: "2026-05-01T20:00:00Z",
  },
  {
    id: "g12", title: "우도 앞 반열기 선상 (제주 특산 어종)",
    hostName: "우도선상러버", hostRating: 4.7, hostCatchCount: 312,
    region: "우도", location: "우도 주변 선상", spotType: "선상", fishingMethod: "선상",
    targetFish: ["반열기", "참돔"], date: "2026-05-26", time: "05:30",
    maxMembers: 6, currentMembers: 2,
    costType: "split", costAmount: 65000, costNote: "선박 대여비 1/n",
    equipmentProvided: true, beginnerWelcome: true,
    description: "제주 특산 반열기(빨간 물고기). 색깔이 정말 예뻐요. 우도 여행객도 환영. 새우 미끼는 제공.",
    tags: ["반열기", "우도", "선상", "초보환영", "제주특산"],
    createdAt: "2026-04-30T11:00:00Z",
  },
  {
    id: "g13", title: "애월 야간 갈치 + 감성돔 2박3일 원정",
    hostName: "애월원정대장", hostRating: 4.5, hostCatchCount: 267,
    region: "애월", location: "애월항 출발 원정", spotType: "선상", fishingMethod: "선상",
    targetFish: ["갈치", "감성돔", "방어"], date: "2026-05-30", time: "16:00",
    maxMembers: 6, currentMembers: 3,
    costType: "split", costAmount: 200000, costNote: "2박3일 선박+숙박+미끼 1/n",
    equipmentProvided: false, beginnerWelcome: false,
    description: "2박3일 제주 원정 낚시. 1일차 야간 갈치, 2일차 갯바위 감성돔, 3일차 선상 방어. 중급 이상만.",
    tags: ["원정낚시", "2박3일", "갈치", "감성돔", "방어", "중급이상"],
    createdAt: "2026-04-29T14:00:00Z",
  },
  {
    id: "g14", title: "제주 전역 낚시 포인트 탐방 (월 1회 정기 모임)",
    hostName: "제주낚시탐험대", hostRating: 4.8, hostCatchCount: 189,
    region: "제주시", location: "매월 다른 포인트", spotType: "방파제", fishingMethod: "찌낚시",
    targetFish: ["감성돔", "볼락", "전갱이"], date: "2026-06-01", time: "06:00",
    maxMembers: 12, currentMembers: 8,
    costType: "split", costAmount: 25000, costNote: "미끼비 + 교통비 1/n",
    equipmentProvided: false, beginnerWelcome: true,
    description: "제주 낚시 포인트를 매달 한 곳씩 탐방하는 정기 모임. 6월 포인트는 투표로 결정 예정.",
    tags: ["정기모임", "포인트탐방", "제주전역", "커뮤니티"],
    createdAt: "2026-04-28T10:00:00Z",
  },
  {
    id: "g15", title: "성산 돌돔·감성돔 원정 (전문 채비 필요)",
    hostName: "성산바다사나이", hostRating: 4.9, hostCatchCount: 478,
    region: "성산", location: "성산 신산리 갯바위", spotType: "갯바위", fishingMethod: "찌낚시",
    targetFish: ["돌돔", "감성돔"], date: "2026-05-28", time: "05:00",
    maxMembers: 3, currentMembers: 1,
    costType: "split", costAmount: 40000, costNote: "크릴+성게 미끼+교통비 1/n",
    equipmentProvided: false, beginnerWelcome: false,
    description: "돌돔 포인트 원정. 원줄 4호 이상, 목줄 3호 이상 필수. 성게 미끼 공동 구매. 고수 동료 구합니다.",
    tags: ["돌돔", "감성돔", "성산", "갯바위", "고수전용"],
    createdAt: "2026-04-27T09:00:00Z",
  },
  {
    id: "g16", title: "한림 비양도 좌대 주말 패키지 (3인 잔여)",
    hostName: "한림좌대단골", hostRating: 4.6, hostCatchCount: 143,
    region: "한림", location: "비양도 좌대", spotType: "좌대", fishingMethod: "좌대낚시",
    targetFish: ["참돔", "벵에돔", "볼락"], date: "2026-05-24", time: "05:00",
    maxMembers: 6, currentMembers: 3,
    costType: "fixed", costAmount: 50000, costNote: "좌대 1인 요금 (미끼 포함)",
    equipmentProvided: true, beginnerWelcome: true,
    description: "비양도 좌대 주말 패키지. 3자리 남았어요. 참돔 포인트라 조황 기대. 초보도 환영합니다.",
    tags: ["좌대", "비양도", "한림", "참돔", "주말"],
    createdAt: "2026-04-26T15:00:00Z",
  },
  {
    id: "g17", title: "서귀포 새벽 갯바위 감성돔 (전날 저녁 합류)",
    hostName: "서귀포새벽꾼", hostRating: 4.8, hostCatchCount: 356,
    region: "서귀포", location: "서귀포 법환 갯바위", spotType: "갯바위", fishingMethod: "찌낚시",
    targetFish: ["감성돔", "벵에돔"], date: "2026-05-27", time: "04:00",
    maxMembers: 4, currentMembers: 2,
    costType: "split", costAmount: 35000, costNote: "크릴+밑밥+교통비",
    equipmentProvided: false, beginnerWelcome: false,
    description: "새벽 4시 포인트 선점. 전날 저녁에 합류해서 함께 이동. 새벽 포인트 경쟁 심하니 일찍 출발.",
    tags: ["감성돔", "새벽낚시", "갯바위", "서귀포", "찌낚시"],
    createdAt: "2026-04-25T11:00:00Z",
  },
  {
    id: "g18", title: "구좌 야간 볼락 + 뒤풀이 (맥주 한 잔)",
    hostName: "구좌볼락헌터", hostRating: 4.5, hostCatchCount: 223,
    region: "구좌", location: "구좌 종달리 방파제", spotType: "방파제", fishingMethod: "루어",
    targetFish: ["볼락"], date: "2026-05-16", time: "20:00",
    maxMembers: 6, currentMembers: 4,
    costType: "split", costAmount: 15000, costNote: "웜 공동 구매 + 뒤풀이비",
    equipmentProvided: false, beginnerWelcome: true,
    description: "야간 볼락 루어 후 근처 편의점에서 맥주 한 잔. 가볍게 즐기는 분위기. 라이트 루어대 있으면 오세요.",
    tags: ["볼락", "야간", "루어", "구좌", "뒤풀이"],
    createdAt: "2026-04-24T20:00:00Z",
  },
  {
    id: "g19", title: "제주 여행 중 갯바위 반나절 체험 (관광객 환영)",
    hostName: "제주낚시안내사", hostRating: 4.7, hostCatchCount: 94,
    region: "서귀포", location: "서귀포 외돌개 인근", spotType: "갯바위", fishingMethod: "생미끼",
    targetFish: ["볼락", "전갱이", "넙치"], date: "2026-05-18", time: "09:00",
    maxMembers: 8, currentMembers: 5,
    costType: "fixed", costAmount: 20000, costNote: "장비+미끼+가이드비 포함",
    equipmentProvided: true, beginnerWelcome: true,
    description: "제주 여행 중 반나절 갯바위 체험 낚시. 장비 전부 제공. 외돌개 관광 후 낚시하기 딱 좋아요!",
    tags: ["관광객환영", "체험낚시", "장비제공", "외돌개", "반나절"],
    createdAt: "2026-04-23T09:00:00Z",
  },
  {
    id: "g20", title: "모슬포 원정 방어 지깅 (고수 4명 모집)",
    hostName: "모슬포선상박사", hostRating: 5.0, hostCatchCount: 721,
    region: "모슬포", location: "모슬포 앞바다 원거리 선상", spotType: "선상", fishingMethod: "루어",
    targetFish: ["방어", "부시리", "소형참치"], date: "2026-05-29", time: "05:00",
    maxMembers: 4, currentMembers: 1,
    costType: "split", costAmount: 120000, costNote: "원거리 선박 4인 1/n",
    equipmentProvided: false, beginnerWelcome: false,
    description: "모슬포 원거리 방어 지깅. 100g~200g 메탈지그 필수. 체력 요구됨. 최소 선상낚시 10회 이상 경험자.",
    tags: ["방어", "지깅", "원거리", "모슬포", "고수전용", "체력필요"],
    createdAt: "2026-04-22T10:00:00Z",
  },
];
