export interface FishData {
  id: string
  name: string
  nameEn: string
  emoji: string
  color: string
  type: 'rock' | 'boat' | 'pier' | 'lure'
  typeLabel: string
  season: string
  bestMonths: number[]
  depth: string
  difficulty: '입문' | '중급' | '고급'
  maxSize: string
  tackle: string
  bait: string
  points: string[]
  tips: string[]
  description: string
}

export const FISH_DATA: FishData[] = [
  { id: 'hairtail', name: '갈치', nameEn: 'Hairtail', emoji: '🐟', color: '#c0c5ce', type: 'rock', typeLabel: '갯바위', season: '여름~가을', bestMonths: [7,8,9,10,11], depth: '10~20m', difficulty: '입문', maxSize: '최대 90cm', tackle: '갈치 전용 다단 채비', bait: '꽁치 토막, 크릴', points: ['한림 갯바위', '서귀포 황금좌대', '모슬포 방파제'], tips: ['야간 입질 집중 (밤 9시~새벽 2시)', '형광 발광체 필수', '물때 9~11물 최적', '크릴보다 꽁치 토막에 굵은 씨알'], description: '제주를 대표하는 낚시 어종. 은빛 띠 모양으로 야간에 특히 활발히 움직인다. 마릿수 낚시 가능해 입문자에게도 좋다.' },
  { id: 'black-porgy', name: '감성돔', nameEn: 'Black Porgy', emoji: '🐠', color: '#6b7a8d', type: 'rock', typeLabel: '갯바위', season: '봄·가을', bestMonths: [3,4,5,9,10,11], depth: '5~15m', difficulty: '중급', maxSize: '최대 60cm', tackle: '반유동/전유동 찌낚시', bait: '크릴, 갯지렁이', points: ['서귀포 황우지해안', '표선 해비치', '한림 비양도'], tips: ['밑밥 동조가 핵심', '조류 약한 곳 공략', '새벽 5~7시 피크타임', '목줄 1.5~2호 추천'], description: '찌낚시의 꽃이라 불리는 어종. 경계심이 강해 채비를 섬세하게 세팅해야 한다. 45cm 이상 대물은 진정한 감성돔 조사의 목표.' },
  { id: 'red-seabream', name: '참돔', nameEn: 'Red Seabream', emoji: '🐡', color: '#e87461', type: 'boat', typeLabel: '선상', season: '봄~여름', bestMonths: [4,5,6,7,8], depth: '20~40m', difficulty: '중급', maxSize: '최대 80cm', tackle: '선상 참돔 채비, 타이라바', bait: '새우 생미끼, 타이라바 루어', points: ['성산 일출봉 앞', '서귀포 외해', '모슬포 앞 여밭'], tips: ['타이라바 슬로우 리트리브', '물때 6~8물 최적', '새우 생미끼에 대물 확률 높음', '수심 탐색 꼭 먼저'], description: '빨간 몸빛과 강한 파워가 매력적인 어종. 제주 선상낚시의 주요 대상어로 1kg 이상 대형도 자주 올라온다.' },
  { id: 'white-groper', name: '벵에돔', nameEn: 'White Groper', emoji: '🐟', color: '#4a5568', type: 'rock', typeLabel: '갯바위', season: '봄~가을', bestMonths: [4,5,6,7,8,9,10], depth: '3~10m', difficulty: '고급', maxSize: '최대 50cm', tackle: '전유동 찌낚시', bait: '크릴, 집어제', points: ['한림 비양도', '서귀포 범섬', '추자도'], tips: ['목줄 1~1.5호 가늘게', '집어제 꼭 사용', '조류 방향 확인 필수', '밑밥과 채비 동조 핵심'], description: '갯바위 낚시 고수들이 즐겨 찾는 어종. 섬세한 채비와 정확한 찌 조작이 필요해 난이도가 높지만 손맛이 탁월하다.' },
  { id: 'rock-fish', name: '볼락', nameEn: 'Rock Fish', emoji: '🐟', color: '#8b6f47', type: 'pier', typeLabel: '방파제', season: '겨울~봄', bestMonths: [11,12,1,2,3,4], depth: '2~6m', difficulty: '입문', maxSize: '최대 30cm', tackle: '지그헤드 0.5~1g + 웜', bait: '소형 웜, 지그헤드', points: ['애월 곽지 방파제', '한림 내항', '성산 방파제'], tips: ['야간 집어등 주변 최고', '지그헤드 0.5g 이하 사용', '테트라포드 틈새 공략', '겨울에도 활발히 활동'], description: '방파제 야간 낚시의 단골 어종. 마릿수가 좋고 입질이 시원해 초보자도 즐기기 쉽다.' },
  { id: 'amberjack', name: '방어', nameEn: 'Amberjack', emoji: '🐟', color: '#2d6a9f', type: 'boat', typeLabel: '선상', season: '가을~겨울', bestMonths: [10,11,12,1,2], depth: '30~60m', difficulty: '고급', maxSize: '최대 120cm', tackle: '지깅 150~300g', bait: '메탈 지그, 생미끼', points: ['모슬포 외해', '서귀포 앞 여밭', '마라도 주변'], tips: ['슬로우 지깅 테크닉 필요', '집어등 주변 노리기', '5kg 이상 대물 주의', '튼튼한 태클 필수'], description: '강력한 파워와 스피드로 유명한 대형 어종. 제주 모슬포가 전국 방어 낚시의 성지다. 10kg 이상 대물도 기대할 수 있다.' },
  { id: 'flounder', name: '광어', nameEn: 'Flounder', emoji: '🐡', color: '#7c8c6a', type: 'lure', typeLabel: '루어', season: '봄~가을', bestMonths: [3,4,5,6,9,10,11], depth: '3~15m', difficulty: '중급', maxSize: '최대 70cm', tackle: '지그헤드 + 웜, 미노우', bait: '생미끼, 웜', points: ['협재 모래밭', '서귀포 방파제', '표선 해수욕장'], tips: ['모래밭-암반 경계 집중', '아침·저녁 황금타임', '느린 리트리브', '바닥 긁기 테크닉'], description: '루어낚시의 대표 어종. 모래밭에 몸을 숨기고 있다가 먹이를 공격하는 습성을 활용해 공략한다.' },
  { id: 'squid', name: '한치', nameEn: 'Squid', emoji: '🦑', color: '#e8a87c', type: 'boat', typeLabel: '선상', season: '여름', bestMonths: [6,7,8,9], depth: '20~50m', difficulty: '입문', maxSize: '최대 40cm', tackle: '에기, 스키머', bait: '에기 (2.5~3호)', points: ['제주 전 해역', '성산 앞바다', '모슬포 외해'], tips: ['집어등 필수', '밤 10시~새벽 2시 피크', '에기 빠른 저킹', '선상에서 수직 에깅'], description: '제주 여름 밤바다의 주인공. 집어등을 켜면 수면 가까이 몰려와 에기에 쉽게 반응한다.' },
  { id: 'tuna', name: '참치', nameEn: 'Tuna', emoji: '🐟', color: '#1a4f7a', type: 'boat', typeLabel: '선상', season: '여름~가을', bestMonths: [7,8,9,10], depth: '50~150m', difficulty: '고급', maxSize: '최대 200kg', tackle: '지깅 200~400g, 포핑', bait: '대형 지그, 포퍼', points: ['모슬포 외해 60해리', '마라도 주변'], tips: ['전용 선착장에서 출항', '체력 소모 극심, 사전 준비', '200g 이상 슬로우 지그', '1인 1낚싯대 원칙'], description: '낚시인의 로망. 제주 모슬포에서 출항해 외해로 나가면 황다랑어, 참다랑어를 만날 수 있다.' },
  { id: 'bass', name: '농어', nameEn: 'Sea Bass', emoji: '🐟', color: '#5a7a5a', type: 'lure', typeLabel: '루어', season: '봄~가을', bestMonths: [4,5,6,7,8,9], depth: '1~5m', difficulty: '중급', maxSize: '최대 100cm', tackle: '미노우, 펜슬베이트', bait: '루어 (미노우 계열)', points: ['애월 해안도로 갯바위', '한림 협재 방파제'], tips: ['새벽·저녁 서핑존 노리기', '큰 파도 직후 입질 집중', '미노우 트위칭 테크닉', '야간 수면 팝핑 효과적'], description: '파워풀한 파이팅이 매력적인 루어낚시 대상어. 파도치는 갯바위에서의 서핑 낚시로 유명하다.' },
  { id: 'mackerel', name: '고등어', nameEn: 'Mackerel', emoji: '🐟', color: '#2d8a6a', type: 'pier', typeLabel: '방파제', season: '가을', bestMonths: [9,10,11], depth: '5~15m', difficulty: '입문', maxSize: '최대 45cm', tackle: '사비키 채비', bait: '사비키 + 크릴', points: ['제주 전 방파제', '한림항', '성산항'], tips: ['가을에 무리 지어 이동', '사비키 채비로 마릿수', '집어제 효과 큼', '아침 일찍 방파제 선점'], description: '가을 방파제 낚시의 단골손님. 군집 이동하는 특성상 마릿수가 폭발적일 때가 있다.' },
  { id: 'parrot-fish', name: '쏨뱅이', nameEn: 'Scorpionfish', emoji: '🐡', color: '#c0392b', type: 'boat', typeLabel: '선상', season: '연중', bestMonths: [1,2,3,4,5,6,7,8,9,10,11,12], depth: '20~60m', difficulty: '입문', maxSize: '최대 35cm', tackle: '선상 묻지마 채비', bait: '지렁이, 크릴', points: ['제주 전 선상', '서귀포 선상'], tips: ['바닥 근처 집중', '예리한 지느러미 주의', '겨울에도 잘 낚임', '손질 시 장갑 착용'], description: '붉은 몸빛이 아름다운 어종으로 독가시를 가지고 있어 취급 시 주의가 필요하다. 탕 요리 재료로 최고.' },
  { id: 'sea-bream', name: '돌돔', nameEn: 'Parrotfish', emoji: '🐠', color: '#8e44ad', type: 'rock', typeLabel: '갯바위', season: '여름', bestMonths: [6,7,8,9], depth: '5~20m', difficulty: '고급', maxSize: '최대 60cm', tackle: '원투 원줄 직결 채비', bait: '성게, 소라', points: ['마라도', '서귀포 범섬', '한림 비양도'], tips: ['성게·소라 미끼가 압도적', '강한 원줄 필수 (12호 이상)', '암초 근처 공략', '여름 한정 시즌'], description: '검은 줄무늬가 특징인 고급 어종. 암초를 박차고 달아나는 힘이 강해 강한 채비와 테크닉이 필요하다.' },
  { id: 'yellowtail', name: '부시리', nameEn: 'Yellowtail', emoji: '🐟', color: '#f39c12', type: 'boat', typeLabel: '선상', season: '봄·가을', bestMonths: [4,5,6,10,11], depth: '20~50m', difficulty: '고급', maxSize: '최대 150cm', tackle: '포핑, 지깅', bait: '포퍼, 지그', points: ['모슬포 외해', '서귀포 외해'], tips: ['수면 포핑으로 유인', '새벽·저녁 피크', '체력 소모 많음', '방어보다 더 빠른 스피드'], description: '방어와 비슷하지만 더 빠르고 역동적인 파이팅이 매력. 포핑 낚시의 최고 대상어.' },
  { id: 'octopus', name: '문어', nameEn: 'Octopus', emoji: '🐙', color: '#9b59b6', type: 'lure', typeLabel: '루어', season: '여름~가을', bestMonths: [7,8,9,10], depth: '5~20m', difficulty: '입문', maxSize: '최대 3kg', tackle: '에기 큰 것 (4호 이상)', bait: '대형 에기, 문어용 루어', points: ['제주 전 방파제 앞', '서귀포 방파제'], tips: ['바닥 느리게 끌기', '큰 에기나 닭머리 미끼', '조류 약한 곳', '밤보다 낮에 유리'], description: '루어낚시로 쉽게 도전 가능. 식재료로도 인기가 높아 잡으면 회로 즐길 수 있다.' },
  { id: 'croaker', name: '보리멸', nameEn: 'Sillago', emoji: '🐟', color: '#d4a94a', type: 'pier', typeLabel: '방파제', season: '여름', bestMonths: [6,7,8,9], depth: '1~5m', difficulty: '입문', maxSize: '최대 30cm', tackle: '원투 모래밭 채비', bait: '지렁이, 청갯지렁이', points: ['협재 해수욕장', '표선 해수욕장', '이호테우'], tips: ['해수욕장 모래밭 원투', '지렁이 미끼 가장 효과적', '여름 낮에도 잘 잡힘', '가족 낚시에 최적'], description: '모래해변에서 즐기는 여름 낚시의 대표 어종. 가족 나들이와 함께 즐기기 좋다.' },
  { id: 'halibut', name: '넙치', nameEn: 'Halibut', emoji: '🐡', color: '#607d8b', type: 'lure', typeLabel: '루어', season: '봄~가을', bestMonths: [3,4,5,6,8,9,10], depth: '5~20m', difficulty: '중급', maxSize: '최대 80cm', tackle: '지그헤드 + 웜', bait: '웜, 생미끼', points: ['협재 모래밭', '이호 앞 모래밭'], tips: ['바닥 모래 위 천천히', '어두운 색 웜 효과적', '아침 일찍 출발', '그림자 주지 말 것'], description: '광어와 비슷하지만 더 크게 자라는 어종. 제주 모래밭에서 루어낚시로 50cm 이상도 노릴 수 있다.' },
  { id: 'bluefish', name: '삼치', nameEn: 'Spanish Mackerel', emoji: '🐟', color: '#1565c0', type: 'boat', typeLabel: '선상', season: '가을', bestMonths: [9,10,11], depth: '수면~15m', difficulty: '입문', maxSize: '최대 80cm', tackle: '트롤링, 지그', bait: '메탈 지그, 미노우', points: ['제주 연안 전체'], tips: ['빠른 리트리브', '날카로운 이빨 주의', '무리 지어 이동', '가을 마릿수 대폭발'], description: '날카로운 이빨과 빠른 질주가 특징. 가을에 떼로 몰려와 선상지깅으로 폭발적인 마릿수를 올릴 수 있다.' },
  { id: 'seabass', name: '능성어', nameEn: 'Grouper', emoji: '🐠', color: '#4a235a', type: 'rock', typeLabel: '갯바위', season: '연중', bestMonths: [1,2,3,4,5,6,7,8,9,10,11,12], depth: '15~40m', difficulty: '고급', maxSize: '최대 100cm', tackle: '원투, 지깅', bait: '살오징어, 생미끼', points: ['마라도', '서귀포 범섬', '추자도'], tips: ['암초 틈새 공략', '강한 채비 필수', '살오징어 미끼 효과적', '제주 고급 어종'], description: '제주 바다의 대형 고급 어종. 암초에 붙어 사는 습성 때문에 공략이 어렵지만 성공하면 엄청난 손맛을 선사한다.' },
  { id: 'cutlassfish', name: '오징어', nameEn: 'Common Squid', emoji: '🦑', color: '#e67e22', type: 'pier', typeLabel: '방파제', season: '봄·가을', bestMonths: [3,4,5,9,10,11], depth: '5~20m', difficulty: '입문', maxSize: '최대 45cm', tackle: '에기 2.5~3호', bait: '에기', points: ['제주 전 방파제', '한림항', '성산항'], tips: ['집어등 있으면 최고', '저녁~밤 활발', '에기 색상 교체 전략', '수심 변화 주며 탐색'], description: '에깅 낚시 입문에 딱 좋은 어종. 봄과 가을 방파제에서 에기 하나로 마릿수 조과를 기대할 수 있다.' },
]
